### ISSUE TITLE
Is Host Header Specified

### ISSUE THREAD

**Issue by zanes2016** [olivere/elastic#1038]
AWS ElasticSearch requires that the `Host: [host]` HTTP header be specified as stated in the [documentation](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-handling-errors.html#aes-troubleshooting-host-header). I was wondering if this is set for us or if we need to manually specify this for ES clients.

**Comment by olivere** [comment]
Given that we’re using the official AWA SDK for Go, I assume they’re handling this correctly. I didn’t dig into the details of that SDK. Also, the Host header is required as of HTTP/1.1 (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host), so I’m pretty sure that works fine because it’s done by the standard library on the protocol level.

Let me know if you find otherwise.
