### ISSUE TITLE
Filter path is applied only to the first request of ScrollService

### ISSUE THREAD

**Issue by damianpietruszewski** [olivere/elastic#1068]
### Which version of Elastic are you using?

[x] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
ScollService uses defined filter path in every subsequent search scroll request.

### Please describe the actual behavior
ScollService uses defined filter path only in the first request.
Next requests don't contain filter path and fetch too much.

### Any steps to reproduce the behavior?
Use filter path (e.g. `FilterPath("hits.total", "hits.hits._id")`) with ScrollService. 
Set query/size in such a way that you will need more than one request to fetch data. 
Execute two requests and compare them.

**Comment by olivere** [comment]
Oh. I have to test that. I'm pretty sure that ES remembered the settings from the initial call in subsequent calls. Otherwise we need to see if we have to copy [this block](https://github.com/olivere/elastic/blob/release-branch.v6/scroll.go#L381-L410) over [here](https://github.com/olivere/elastic/blob/release-branch.v6/scroll.go#L487-L490).

**Comment by olivere** [comment]
I can reproduce the issue and it will be fixed in 6.2.18. However, it is not documented which of the parameters used in the initial scroll requests are allowed to be passed into subsequent scroll requests (e.g. `size` causes an error while `filter_path` seems to work allowed). So in order to guard against new issues, I will only copy over the `filter_path` in subsequent requests for now. If there are other parameters to copy over, we need to file a new issue.

**Comment by olivere** [comment]
Also fixed in 7.0.1.
