### ISSUE TITLE
Empty result do.request 

### ISSUE THREAD

**Issue by SArtemJ** [olivere/elastic#1087]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
I'm create curl request to es7 
```
{
  "query": {
    "bool": {
      "must": [
        { "match": { "FirstName": "John" }},
        { "match": { "LastName": "Johnson"}}
        ]
    }
  }
}
```
Search request ```http://localhost:9200/users/_search``` return's me result
```
{
    "took": 3,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 1,
            "relation": "eq"
        },
        "max_score": 7.195937,
        "hits": [
            {
                "_index": "users",
                "_type": "_doc",
                "_id": "c9921df6-64fd-4042-8c90-9b9b2cb37a0c",
                "_score": 7.195937,
                "_source": {
                    "FirstName": "John",
                    "LastName": "Johnson"
}}]}}
```

### Any steps to reproduce the behavior?
Create equal request on golang
```
client, _ := elastic.NewClient(elastic.SetURL("http://localhost:9200"))
query := elastic.NewBoolQuery().Must(
		elastic.NewMatchQuery("FirstName", "John"),
		elastic.NewMatchQuery("LastName", "Johnson")

	res, err := client.Search().Index("users").Query(query).Do(context.Background())
	if err != nil {
		log.Println(err)
		return
	}
```
and service return's me zero values
why?  
resul json from golang code to elasticsearch looks like this
```
"bool": {
        "must": [
            {
                "match": {
                    "FirstName": {
                        "query": "John"
                    }}},
            {
                "match": {
                    "LastName": {
                        "query": "Johnson"
                    }}}
        ]
    }
}
```

**Comment by olivere** [comment]
There is no `NewMustQuery`. Can you provide a complete example?

**Comment by SArtemJ** [comment]
> There is no `NewMustQuery`. Can you provide a complete example?

Sorry I mean - NewMatchQuery()

**Comment by olivere** [comment]
First of all, the queries are not the same. In the `curl` example, you specify a `MatchAll`, while in the Go code, you specify a boolean query. Please don't compare apples and oranges.

One of the things why this typically goes wrong is because the `FirstName` and `LastName` fields are of the `text` type, which is analyzed, so an exact match will fail. If you query for `FirstName.keyword` and `LastName.keyword`, this usually succeeds. Without any mapping [these heuristics are used](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html), so you typically get a [`text`](https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html) field with a [`keyword`](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html) sub-field.

If that still goes wrong, let me know.
