### ISSUE TITLE
Aggregation results return when no search hits are found

### ISSUE THREAD

**Issue by agruetz** [olivere/elastic#1093]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[X] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
If there are no search hits then there should be no aggregations.

### Please describe the actual behavior
I am executing a search with aggregations and with I use From and Size in the search that goes past an index where any search hits are returned the aggregations still return results at the size limit of the aggregations.

Maybe this is the expected behavior I am relatively new to Elastic Search but this feels incorrect. Thanks in advance.

### Any steps to reproduce the behavior?
Probably best explained by this code excerpt.

rangeQuery := elastic.NewRangeQuery("@last_upd").Gt("now-1h")

	agg2 := elastic.NewTermsAggregation().Field("region.keyword").Size(2)
	agg3 := elastic.NewTermsAggregation().Field("attributes.ec2_instance_type.keyword").Size(2)
	agg1 := elastic.NewTermsAggregation().Field("account_id.keyword").Size(2)
	agg2 = agg2.SubAggregation("groupby_instance_type", agg3).Size(2)
	agg1 = agg1.SubAggregation("groupby_region", agg2).Size(2)

	q := elastic.NewBoolQuery().Filter(rangeQuery)
	q.Must(elastic.NewTermQuery("source_type", "ec2"))
	q.Must(elastic.NewTermQuery("attributes.resource_state", "running"))

	/*
		searchRequest := elastic.NewSearchRequest().Aggregation("groupby_account_id", agg1).From(0).Size(100000).Query(q)
		d, e := searchRequest.Body()
		if e != nil {
			panic(e)
		}
		println(d)
	*/

	es, err := client.Client.Search("metadata").Query(q).Aggregation("groupby_account_id", agg1).From(0).Size(2).Do(ctx)
	if err != nil {
		log.Panicf("%v\n", err)
	}

**Comment by olivere** [comment]
Hi! There's two parts to your question.

First, elastic is a dumb client. It simply returns what ES returns. There is no logic involved, just serialization. In other words: If ES _does_ reply something, then elastic _will_ reply something.

Second, you might want aggregations to return even if there are no search results. Consider an online store where you have search results and a faceted filter for brands. Your users probably want a list of available brands to pick from even if there search results didn't provide any hits. That's why you need [`PostFilter`](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/search-request-post-filter.html). Here's another description that you might find useful, although outdated: https://www.elastic.co/guide/en/elasticsearch/guide/current/_post_filter.html

**Comment by agruetz** [comment]
Makes sense. Thank you for clarifying.
