### ISSUE TITLE
 The length of the BulkProcess Id field should be checked

### ISSUE THREAD

**Issue by Dik1s** [olivere/elastic#1097]
### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

----

When I was using BulkProcessor to index data, I found that after setting the long _id field, the speed of the program would be greatly reduced. It would take a few seconds to process a piece of data. This is not normal.
Then I looked at the source of the elasticsearch and the code for the blukprocessor. I think in the code:

` https://github.com/olivere/elastic/blob/release-branch.v7/bulk_index_request.go`

Line 90 This method should check if the length of the set id is less than or equal to 512.

Reference link:

https://github.com/elastic/elasticsearch/blob/2d29807b9cdd2bb3e78dbd2f8b1d33fa9d35081e/server/src/main/java/org/elasticsearch/action/index/IndexRequest.java

219 Line

`        if (id != null && id.getBytes(StandardCharsets.UTF_8).length > 512) {
            validationException = addValidationError("id is too long, must be no longer than 512 bytes but was: " +
                            id.getBytes(StandardCharsets.UTF_8).length, validationException);
        }`

**Comment by olivere** [comment]
The error is server-side, so it will be raised if you do this and call the server. The client will simply pass the exception along and you should check it. We don’t check all the possible exceptions client-side because then it would be impossible for us to follow the speed of changes on the server-side. What if the people working on Elasticsearch would increase or decrease the length limit? We would have an incorrect behaviour in the client immediately.
