### ISSUE TITLE
Update document in v7: invalid_type_name_exception

### ISSUE THREAD

**Issue by m-lukas** [olivere/elastic#1099]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

I'm using the Update() function on the elastic.Client Interface to update an proved existing document in my index using the following code (shortened):
```
//client was defined and connection established before
index := "users"
id := "<some id>"
updateDate := map[string]interface{}{"bio": "test"}

ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
defer cancel()

resp, err := client.Update().Index(index).Id(id).Doc(updateData).Do(ctx)
```

The code should update the bio field within the mapped user document.
The mapping is defined as followed:

//The multi-line apostrophes are replaced with " for Markdown
```const userMapping = "
{
	"mappings":{
		"properties":{
			"login":{
				"type":"keyword"
			},
			"email":{
				"type":"keyword"
			},
			"name":{
				"type":"text"
			},
			"bio":{
				"type":"text"
			}
		}
	}
}"

client.CreateIndex("users").BodyString(mapping).Do(ctx) //context previously defined
```

> used module: "github.com/olivere/elastic/v7"

There is no further type defined and it uses "_doc" as default type according to the conventions of elastic v7

### Please describe the actual behavior

If I'm trying to update an existing user, it returns me the following error:

```elastic: Error 400 (Bad Request): Document mapping type name can't start with '_', found: [_update] [type=invalid_type_name_exception]```

Hereby I found the error to be caused by:

//update.go in github.com/olivere/elastic/v7
```
if b.typ == "_doc" {
	path, err = uritemplates.Expand("/{index}/_update/{id}", map[string]string{
		"index": b.index,
		"id":    b.id,
	})
} else {
	path, err = uritemplates.Expand("/{index}/{type}/{id}/_update", map[string]string{
		 "index": b.index,
		 "type":  b.typ,
		 "id":    b.id,
	 })
}
```

This seems to use "_update" as invalid type.

### Any steps to reproduce the behavior?

This error should be reproduceable by using the default UpdateService.

**Comment by olivere** [comment]
According to the [REST API spec for 7.1](https://github.com/elastic/elasticsearch/blob/v7.1.0/rest-api-spec/src/main/resources/rest-api-spec/api/update.json#L6-L7), the paths should be OK. But the error message in fact states that `_update` is mistakingly used as the document type name.

We can safely fix this bug by using [the same approach as the official driver](https://github.com/elastic/go-elasticsearch/blob/master/esapi/api.update.go#L77-L86). It should be a one-liner.

**Comment by olivere** [comment]
I think we should just change the above to:

```
if b.typ == "" || b.typ == "_doc" {
	path, err = uritemplates.Expand("/{index}/_update/{id}", map[string]string{
		"index": b.index,
		"id":    b.id,
	})
} else {
	path, err = uritemplates.Expand("/{index}/{type}/{id}/_update", map[string]string{
		 "index": b.index,
		 "type":  b.typ,
		 "id":    b.id,
	 })
}
```

**Comment by olivere** [comment]
@m-lukas I've tries to fix the issue in e13dcdb46e43e6b1e14037127babdde90192c034 with the explanations described above. However, it should have been okay even before that, because the `type` is set to `_doc` by default [here](https://github.com/olivere/elastic/blob/release-branch.v7/update.go#L47). So if your code doesn't touch `type` again, e.g. by somehow calling [`Update.Type(...)`](https://github.com/olivere/elastic/blob/release-branch.v7/update.go#L59-L65), it should've always been using [this URL template](https://github.com/olivere/elastic/blob/release-branch.v7/update.go#L205-L208), resulting in a `POST /{index}/_update/{id}` call that is correct and works fine, as we tested with ES 7.1.0.

Can you try to find a test case that illustrates your problem, maybe by tweaking [this test case](https://github.com/olivere/elastic/blob/release-branch.v7/update_integration_test.go#L14-L63)?

**Comment by m-lukas** [comment]
@olivere Thank you very much already! I will try it out tomorrow and send you the result :)

**Comment by olivere** [comment]
Should be okay.
