### ISSUE TITLE
elasticsearch Write problem

### ISSUE THREAD

**Issue by xufei56789** [olivere/elastic#1129]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[V] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I hope to insert data into elasticsearch

### Please describe the actual behavior
I am using the docker container to build an elasticsearch environment and a golang environment.
The version of elasticsearch is 7.1.1
Elasticsearch only added network.host: 0.0.0.0 in the configuration file elasticsearch.yml
The connection is normal,Webpage  http://127.0.0.1:9200/ opens normally
`	url := "http://elasticsearch:9200"
	client, err := elastic.NewClient(elastic.SetURL(url),
		elastic.SetSniff(false))
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(-1)
	}`
No abnormal connection to Elasticsearch

But use
`client.Index().
		Index("sns").
		Type("post").
		BodyJson(p.post).
		Do(context.Background())`

Card for a long time, then an error

**elastic: Error 503 (Service Unavailable): blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];[SERVICE_UNAVAILABLE/2/no master]; [type=cluster_block_exception]**

**Comment by olivere** [comment]
The problem seems to be unrelated to the library. If you misconfigure Elasticsearch on Docker, it might return internal IPs, which will be picked up by the library in a process called sniffing. Simply disable sniffing if you don't need load-balancing (`elastic.SetSniff(false)` and `elastic.SetHealthcheck(false)`) and see if this solves your issues.

See also https://github.com/olivere/elastic-with-docker for a (rather old) example illustrating different issues around Docker and Elasticsearch and Elastic.
