### ISSUE TITLE
Correct way to use elastic

### ISSUE THREAD

**Issue by aanm** [olivere/elastic#113]
I've been using elastic a while ago but I'm not sure if I'm doing it the correct way.
I've a server that receives requests, process them and then reply and close connection (like a normal server).
I've a database interface that has a method `NewDB()` to return a DB struct, in this case is MyElastic.
```go
type MyElastic struct {
	*elastic.Client
}

func NewMyElastic(ip, port string) (MyElastic, err) {
        var c MyElastic
	if c.Client, err = elastic.NewClient(
		elastic.SetURL("http://"+ip+":"+port),
		elastic.SetMaxRetries(10),
		elastic.SetSniff(false),); err != nil {
		return c, err
	}
}
```

Now, for every request the server receives, I'm running `NewDB()` which runs `NewMyElastic()` and returns me a fresh elastic Client.
Is this the right approach? I don't feel like it but I also feel bad if I use a unique MyElastic for every request.

**Comment by olivere** [comment]
Hi there!  To use Elastic, you typically create one client per Elasticsearch cluster and use it everywhere in your application. You should initialize it once. See [here](https://gist.github.com/olivere/eaee7a20524ab2beba71) for an example.

Also, there's a section about the [Client](https://github.com/olivere/elastic/wiki/Client) and its configuration parameters in the [Wiki](https://github.com/olivere/elastic/wiki).

HTH

**Comment by aanm** [comment]
@olivere Thank you for the response.
Two more things.
1) There's a Start() and Stop() funcs available. Should that be used for any particular reason?
2) How do you advice testing a program that has elastic? Mocking it?

**Comment by olivere** [comment]
@aanm You're welcome.

`Start` and `Stop` are used to start/stop the background services that Elastic will start when (successfully) creating a new Client. These background services are run as Goroutines. There are two of these.

First, there's the [health checker](https://github.com/olivere/elastic/wiki/Healthcheck) that periodically checks if the nodes that Elastic knows about are still there and "healthy". It also tries to reanimate nodes that are marked as "dead" e.g. due to a connection problem in recent HTTP requests.

Second, there's the [sniffer](https://github.com/olivere/elastic/wiki/Sniffing). It periodically runs and checks if your cluster has changed in terms its nodes. If you e.g. add a new node, Elastic will find out eventually. If you remove a node, Elastic should also be able to detect that and will skip that node for further requests. For now, Elastic uses simple round-robin to send queries. It turned out to be "good enough" for most scenarios.

Notice that you can disable health checks and sniffing altogether, if you don't need that or it doesn't work with your network settings. E.g. Elasticsearch on Docker by default publishes an internal IP address that cannot be accessed from the outside, so you must either reconfigure Elasticsearch or disable sniffing.

Regarding testing, I think it depends if you want to do integration tests or unit tests. With integration tests, it should be okay to create a new Client and either use it throughout all your tests or create a Client and make sure to stop (using Stop) it after your test is done. It might even be acceptable to not stop it if you only have a few tests because the Goroutines would stop as soon as your tests are done. With unit tests, you probably want to manually set up responses from Elastic which you might do quite simply, I suppose.

When I test my services, I generally use Elastic under the hood. I access my data access adapter via an interface and typically set up two implementations for that adapter, a "live" store and a "fake" store. Before I start my tests, I make sure that my data access adapter/repository will use the fake store and can I can mock the response with these. Some pseudo-code:

```go
type Repository interface {
  Get(string) (*Entity, error)
}

var Store Repository

func init() {
  Store = &LiveRepository{}
}

type LiveRepository struct {
}

func (r *LiveRepository) Get(id string) (*Entity, error) {
  // Access data here with e.g. Elastic
}

type FakeRepository struct {
  OnGet(string) func(string) (*Entity, error)
}

func (r *FakeRepository) Get(id string) (*Entity, error) {
  if r.OnGet != nil {
    return r.OnGet(id)
  }
  return nil, errors.New("Get should not have been called")
}

// In your tests

func TestRepository(t *testing.T) {
  fake := &FakeRepository{}
  fake.OnGet = func(id string) (*Entity, error) {
    if id == "1" {
      // ... success
    }
    return nil, errors.New("should not have happened")
  }
  Store = fake

  // Test a part of your program that should retrieve entity with Id="1"
}
```

I think you get the idea by now.

HTH

**Comment by aanm** [comment]
@olivere I think I got it, I'll try on my own. I'll ping you if I need more help. Thank you!
