### ISSUE TITLE
golangci-lint lists some warnings. Can help fixing.

### ISSUE THREAD

**Issue by akshayjbhat** [olivere/elastic#1168]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
I ran a golangci-lint and found lot of warnings (155 excluding tests). Let me know if I can help fixing some.

**Comment by olivere** [comment]
I’ve been running staticcheck and other linters as well, from time to time. It really depends on the kind of issue. E.g. I won’t change Id to ID now, because that’d be a breaking change. And documentation is also missing in a lot of places. But if you find a bug with the linters, I’m perfectly happy if you’d fix it and send a PR. Thanks for your time and effort.
