### ISSUE TITLE
Deleting a missing document returns a non-nil error

### ISSUE THREAD

**Issue by dobegor** [olivere/elastic#1194]
### Which version of Elastic are you using?

[ *] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
`err` is nil and `deleteResponse` has `Status` = `not_found`.

### Please describe the actual behavior

`err` is non-nil and `deleteResponse` has `Status` = `not_found`.
### Any steps to reproduce the behavior?
```golang
deleteResponse, err := s.ES.Delete().Index("test").Id("someID").Do(ctx)
```

### Motivation

I know that ES returns a 404 status code for that request (which is in turn a questionable decision on itself), but it would be much more reasonable and Go-way to _not_ do this in case of this library.

I.e. to properly handle this situation (considering that deletion should be idempotent), one would need to write something like this:

```golang
deleteResponse, err := s.ES.Delete().Index("test").Id("someID").Do(ctx)

if err != nil {
  if deleteResponse != nil && deleteResponse.Result == "not_found" {
    // not actually an error
    return nil
  }

  return err
}
```

Which isn't idiomatic Go.

**Comment by olivere** [comment]
As you said, ES returns a 404 when trying to delete a document that doesn't exist. That's an error.

This library doesn't try to draw its own conclusions of how ES should work, but only provides a (hopefully) transparent client into what ES does. So if ES returns a 404, so should we. Otherwise you'd get a ton of issues here in how this client doesn't do what ES does, and how it works wonderful with `curl` but not with elastic.

I think when implementing the Delete API, I was looking at what the official clients do. And IIRC, they raise an error when Delete API returns a 404. So do we. There even [is a test for it](https://github.com/olivere/elastic/blob/release-branch.v7/delete_test.go#L70-L76).

So, the philosophy of elastic has been: We need to do what ES does, and we need to do what the official clients do. And: Try not to break stuff.

But don't worry, there's a rather simple pattern you can use to check the "not found" case:

```
resp, err := client.Delete()...Do(ctx)
if elastic.IsNotFound(err) {
  // not found error
}
if err != nil {
  // some other error
}
...
```

BTW: Even standard library follows this pattern in a few cases, e.g. when trying to [stat a file that doesn't exist](https://golang.org/pkg/os/#IsNotExist).

**Comment by dobegor** [comment]
Thanks for the quick response! I agree with your point.

But I think that using `elastic.IsNotFound` to check that deletion did not succeed due to missing document isn't safe, because you may get 404 code in case that elasticsearch is behind a proxy/load balancer/service mesh/etc, and, making deletion succeed on `elastic.IsNotFound(err) == true` would yield incorrect state in this case.

**Comment by olivere** [comment]
Elastic is just a library that interacts with ES—plain and simple. It cannot possibly figure out all network topologies you might have in use. If your infrastructure returns 404 in unexpected ways, that's a problem of your infrastructure.
