### ISSUE TITLE
Can we do Index operations by Alias names?

### ISSUE THREAD

**Issue by mangatmodi** [olivere/elastic#1229]
Update: From the code - https://github.com/olivere/elastic/blob/release-branch.v6/delete.go#L176, it seems that Index and Alias are interchangeable just like ES API, could you please confirm?

### Which version of Elastic are you using?
[X] elastic.v6 (for Elasticsearch 6.x)
### Please describe the expected behavior
How could I operate on aliases directly without using index names? Basically I want to delete a given Id by an aliase name. The only solution I could see is to get all the aliases and then operate on them in a loop like below
```
	a,err := es.Aliases().Alias(alias).Do(context.Background())
	idx := a.IndicesByAlias(alias)

```

But this will require multiple ES delete operations.

### Please describe the actual behavior
Is there any API where I could delete in all the indices. For e.g.
	`a,err := es.Aliases().Alias(alias).Delete().Do(context.Background())`
### Any steps to reproduce the behavior?
N.A.

**Comment by olivere** [comment]
The [documentation states](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/indices-add-alias.html):

> An index alias is a secondary name used to refer to one or more existing indices.
>
> Most Elasticsearch APIs accept an index alias in place of an index name.

I can confirm that indexing documents, removing documents, updating documents etc. works fine when you specify the name of an alias instead of the index name. In fact, it's one of the best features of Elasticsearch, as you can easily do index management with aliases.

What you couldn't do until lately is to post a document to an alias and expect it to update multiple indices. With ES 7.x, you [can do something like that](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html#aliases-write-index).

By reading the official documentation and a bit trial and error, you will sort it out.

**Comment by mangatmodi** [comment]
Thanks man! Much appreciated!
