### ISSUE TITLE
Division between two sum fields

### ISSUE THREAD

**Issue by kiriakosbour** [olivere/elastic#1246]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)

### Please describe the expected behavior
I would like to ask if it is a way to use division between t wo sum fields
"aggs": {
  "sum_1": {
    "sum": {
      "field": "flag_barisolve"
    }
  },
  "sum_2": {
    "sum": {
      "field": "flag_anagrafe"
    }
  },
  "division": {
    "bucket_script": {
      "buckets_path": {
        "my_var1": "sum_1",
        "my_var2": "sum_2"
      },
      "script": "params.my_var1 / params.my_var2"
    }
  }
}

**Comment by olivere** [comment]
I'm not sure if I understood you correctly...

We already have `BucketScript`. [Here's a test for it](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_pipeline_bucket_script_test.go).

Most of the existing aggregations have an integration test in [`search_aggs_test.go`](https://github.com/olivere/elastic/blob/release-branch.v7/search_aggs_test.go). I bet you can get inspiration from that.

Let me know if that didn't solve your question. An executable code snippet that illustrates your problem is always best.

**Comment by kiriakosbour** [comment]
Tkhank you very much
