### ISSUE TITLE
AliasService.AddWithFilter takes pointer to interface

### ISSUE THREAD

**Issue by Bo0mer** [olivere/elastic#126]
Hi,

Here https://github.com/olivere/elastic/blob/master/alias.go#L49, the method `AddWithFilter` takes pointer to `Filter`, which is declared to be an interface. Is this really needed?

This works ok:
```go
filter := elastic.NewTermsFilter("something", "else")
filterInterface := elastic.Filter(filter)
esClient.Alias().AddWithFilter(indexName, aliasName, &filterInterface).Do()
```
However, this does not:
```go
esClient.Alias().AddWithFilter(indexName, aliasName, elastic.NewTermsFilter("something", "else")).Do()
```

**Comment by olivere** [comment]
Hi there! No, it's not. I guess these lines have been written when I wasn't too familiar with Go. Sorry for that.

I don't want to change it for v2 because that'd be a breaking change. However, I will change it for elastic v3 (currently in beta and targeting Elasticsearch 2.0).

Thanks for reporting!

**Comment by olivere** [comment]
Oh. In fact I have [changed it already](https://github.com/olivere/elastic/blob/release-branch.v3/indices_put_alias.go#L49) :-)
