### ISSUE TITLE
Support for Cluster update settings API

### ISSUE THREAD

**Issue by kamolhasan** [olivere/elastic#1274]
We've been working on a project where we need to perform the following query to disable shard allocation using the client.

```
PUT _cluster/settings
{
  "persistent": {
    "cluster.routing.allocation.enable": "primaries"
  }
}
```
From your `README.md`, it seems like you haven't provided support for this endpoint yet. 

Is there any way to perform this using the existing client library?
Or anything else. 

### Which version of Elastic are you using?

- elastic.v7

**Comment by apgmckay** [comment]
Is there any update on this it's been 4 years and still not implemented?

**Comment by olivere** [comment]
@apgmckay This project has been [deprecated for many years now](https://github.com/olivere/elastic/issues/1533). It's still around because some people still rely on it. But with the decision of Elastic to build their own [official Go client](https://github.com/elastic/go-elasticsearch), it doesn't make sense to "compete" against it with an unofficial, community-supported client. The speed with which they add features is way too high for that, and the ability to plan ahead is not a given. This project won't get new features or support new versions of Elasticsearch. You should update your code to use the [official client](https://github.com/elastic/go-elasticsearch). They, e.g., already [support the cluster settings API](https://github.com/elastic/go-elasticsearch/blob/main/esapi/api.cluster.put_settings.go).

**Comment by apgmckay** [comment]
Thanks for the reply @olivere totally makes sense.

The only reason I was asking was because this was package is a dependency of [this](https://github.com/opensearch-project/terraform-provider-opensearch/blob/main/provider/resource_opensearch_cluster_settings.go#L16) open search  terraform provider has a dependency on this un API.

But yeah... I'll try and see if I can get them/or even just do it myself to change to the official Go client for elastic 🤔 

Thanks again.

**Comment by olivere** [comment]
@apgmckay Thanks for the clarification. Just a final note: As a workaround, you (or, better, the Terraform provider) can always use [`PerformRequest`](https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L1312) directly to implement calls into Elasticsearch that are not supported by the DSL.

**Comment by apgmckay** [comment]
Interesting thanks for the share @olivere I'll give that a look.
