### ISSUE TITLE
Cannot use TrackTotalHits when making ES query

### ISSUE THREAD

**Issue by amanjain97** [olivere/elastic#1276]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
I am trying to make `track_total_hits: false` in `search_service`. But it seems that it is not available in Search_service. 

### Please describe the actual behavior
It is available in `SearchSource` which we can use in `SearchService` but I am not sure is it a bug or there is another way to use it.

### Any steps to reproduce the behavior?
1. Create elasticsearch client for Search() method. There I cannot use `TrackTotalHits` but can use `TrackScores`

**Comment by olivere** [comment]
Yes, seems like it’s missing. A workaround would be to set up a SearchSource yourself and pass it into Search service. But I’m adding it next release.

TrackTotalHits should be false by default, so maybe in your use case it doesn’t make a difference.

**Comment by amanjain97** [comment]
Thanks for the reply.  I am actually making a PR regarding this. Please review when you have time.

**Comment by amanjain97** [comment]
> TrackTotalHits should be false by default, so maybe in your use case it doesn’t make a difference.

@olivere  I think it is set as true. 
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#track-total-hits-10000-default

**Comment by olivere** [comment]
In ES 6.x, `track_total_hits` can be a boolean and, when `true`, will accurately return the number of matching documents; otherwise, it will just find a rough estimate (that is faster to calculate).

In ES 7.x, `track_total_hits` can be a boolean or a number that sets an upper bound for which there will be accurate results.

See [here](https://github.com/elastic/elasticsearch/blob/v7.5.2/server/src/main/java/org/elasticsearch/search/builder/SearchSourceBuilder.java#L262-L266).

I'm pretty confident that it is `false` (or `10.000`) by default and number of documents are only tracked accurately only up to 10.000 hits, and that's described [the link you posted](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/breaking-changes-7.0.html#track-total-hits-10000-default) as well.

**Comment by amanjain97** [comment]
Oh Ok. Thanks for the information. I have checked too.

**Comment by amanjain97** [comment]
@olivere Can you please take a look as it is mentioned in this code documentation that `default is true`. See [here](https://github.com/olivere/elastic/blob/release-branch.v6/search_source.go#L178)

**Comment by olivere** [comment]
If it isn't explicitly set by you, it takes the server's default value. That documentation is provided by the REST API specification from the good people at ES. So if you don't specify `TrackTotalHits` explicity, elastic [won't serialize it](https://github.com/olivere/elastic/blob/release-branch.v6/search_source.go#L457-L459) and the server will pick its default value. The client shouldn't specify the default.

**Comment by olivere** [comment]
Fixed in next release of v6.
