### ISSUE TITLE
[blkRequest] NewBulkIndexRequest aysnc post data has high CPU load?

### ISSUE THREAD

**Issue by feng1o** [olivere/elastic#1320]
### Which version of Elastic are you using?
>  elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
>  olivere:  olivere/elastic.v5
   i use  async BulkIndexRequest post data to ES； but i found the cpu load is very high 
   
   througthoutput: 80M/s
   cpu load :  5 core (500%)
   mem:  500M
   
   use pprof  analysis:
            
![图片](https://user-images.githubusercontent.com/10048132/80465631-f13d7a00-896d-11ea-9129-38fa3b7c67b0.png)

### Please describe the actual behavior
why cpu load is so high?   Whether there is improper config?  tks

**Comment by olivere** [comment]
JSON serialization and deserialization in Go could be better (and [people complain about it since 2013](https://github.com/golang/go/issues/5683)). There are several reports and options on the internet about that, just Google for [golang json performance](https://www.google.com/search?q=golang+json+performance).

You might optimize the serialization side of your code by using a [different JSON decoder](https://github.com/olivere/elastic/wiki/Decoder). For bulk indexing, you a) can [enable easyjson](https://github.com/olivere/elastic/blob/release-branch.v7/bulk_index_request.go#L67-L75) or b) not serialize the JSON requests in the library but prepare them yourself and pass them as e.g. strings ([`BulkableRequest` might help here](https://github.com/olivere/elastic/blob/release-branch.v7/bulk_request.go#L13-L17)).
