### ISSUE TITLE
(*BulkIndexRequest).Doc should deep copy the parameter

### ISSUE THREAD

**Issue by Sasasu** [olivere/elastic#1335]
### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[x] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### code
```go
var reader = bufio.NewReader(os.Stdin)
var payLoad = Payload{}
for {
	var text, err = reader.ReadBytes('\n')
	if err != nil {
		break
	}
	payLoad.Reset()
	err = json.Unmarshal(text, &payLoad)
	if err != nil {
		panic(err)
	}
		
	// do some on payLoad

	indexRequest := elastic.NewBulkIndexRequest().Index(outputElasticIndexName).Id(payLoad.UUID).Doc(payLoad)
	outputBulkProcess.Add(indexRequest)
}
```
### Please describe the expected behavior
load data quickly. no data corruption no panic.

> elastic do JSON serialize in .Doc() function call. or
> some document can be found, .Doc() function will shadow copy the parameter.

### Please describe the actual behavior
some race occurred and panic in std JSON serialization.

**Comment by olivere** [comment]
Just by looking at the code, I can only guess what's happening here. You're mentioning data races especially, and in your code there is no concurrency. Please provide a reproducible test to see if there's an issue or not.

We are running millions of document updates in production here every day with the same kind of logic, and it's running smoothly. When you have data races, it is because several goroutines access the same data concurrently; I can't see why that might be happening in the example above. If you have such a use case, make sure that either access to the data is properly protected, or prepare the data in such a way that the goroutines do not access the same data in the first place.

With regards to your question: It's not the responsibility of the library to make sure the data is properly passed into it, it's the callers responsibility.
