### ISSUE TITLE
Implement Source Filtering

### ISSUE THREAD

**Issue by autochthe** [olivere/elastic#135]
Elasticsearch has a way to return partial source documents that is more powerful than the fields parameter.  This would extremely useful functionality.  See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html

**Comment by autochthe** [comment]
I noticed there is an open PR #103.  I would like to note that for my specific use case, I wish to use filtering during a scan/scroll request, which is functionality supported by Elasticsearch.  I noticed that it is currently possible to perform a regular search request with a FetchSourceContext, but I don't think it is currently possible to set SearchSource manually with ScanService or ScrollService.

**Comment by olivere** [comment]
Hi!

When implementing Elastic I tend to use the Java client as the "source of truth". When initially implementing source filtering I noticed that the Java client always uses the `FetchSourceContext` class under the hood. All functions related to source filtering in Java basically create an instance and forward to that class. So I implemented [`FetchSourceContext`](https://github.com/olivere/elastic/blob/master/fetch_source_context.go) and asked the client programmer set it up correctly and pass it into the services, e.g. [`Get`](https://github.com/olivere/elastic/blob/master/get.go#L88), [`MultiGet`](https://github.com/olivere/elastic/blob/master/multi_get.go#L153), [`MoreLikeThis`](https://github.com/olivere/elastic/blob/master/search_queries_more_like_this.go#L345), [`InnerHit`](https://github.com/olivere/elastic/blob/master/inner_hit.go#L89) etc.

So Elastic has source filtering, but it's probably not as visible as it should be. One example is your use case: How do I use source filtering with `Scan`? I'm not sure it works, but can you try this:

```go
// Init search source
src := elastic.NewSearchSource(...)
...

// Use scan service
scan := client.Scan(...)
scan = scan.Query(src)  // as SearchSource implements the Query interface this should be okay
...
``` 

It's a hack, I know. And I'm thinking of better ways, like directly offering to set the `SearchSource` in `Scan`.

However, I cannot see how to use source filtering with `Scroll` though. Do you have any examples?

**Comment by autochthe** [comment]
Hmmm Interesting.  I didn't know you could give a `SearchSource` to `ScanService` like that.  That definitely is good enough for my purposes, but I would be in favor of a more explicit method.  It would certainly be convenient to be able to give a `FetchSourceContext` to `ScanService` directly.  Have you considered embedding `SearchSource` as an [anonymous field](https://golang.org/ref/spec#Struct_types) in all the `*Service` objects?  That would allow access to all the underlying functionality of `SearchSource`.  However, the `ScanService.Query()` hack will work well enough for my purposes, so no need to rush what may potentially be a major redesign.

As for using source filtering with scroll, I guess I'm not entirely clear on the exact differences between scan and scroll.  I just know that using the REST API, you can do something like this:

    curl 'localhost:9200/analysis/_search?scroll=1m&search_type=scan' -d '{"_source": "group", "query":{"term":{"group.feild1":"foo"}}}'

Which gives the usual `_scroll_id`, and when you make scroll requests to the `/_search/scroll` endpoint, you get only the document subtree under the "group" key.  Not sure if this technically a scan or a scroll.  Like I said, I'm a bit unclear on the difference.

**Comment by autochthe** [comment]
So I just tried passing a `SearchSource` to `ScanService.Query()`, however, it seems to be improperly nesting the source within a "query" key.

For example, if I try this (`elasticClient` is an `elastic.Client`):

    elasticClient.Scan("index1").KeepAlive("1m").Query(
        elastic.NewSearchSource().FetchSourceContext(
            elastic.NewFetchSourceContext(true).Include("group"),
        ).Query(
            elastic.NewTermFilter("group.field1", "foo"),
        ),
    ).Do()

It gives me a query parsing exception, which seems to be because it is improperly nesting the output of `SearchSource.Source()` into a "query" key:

    {"query":{"_source":{"excludes":[],"includes":["group"]},"query":{"term":{"group.field1":"foo"}}}}

The correct output should be:

    {"_source":{"excludes":[],"includes":["group"]},"query":{"term":{"group.field1":"foo"}}}

**Comment by olivere** [comment]
Well, I'm sorry that it didn't work out as I thought it would. It was worth a try.

I think I will review the situation around this and make `SearchSource` (and friends) available to `Scan` in the same way as I did in `Search`.

The situation around `Scan` and `Scroll` is a bit rough. It's not bad, but a bit off because at that time I misunderstood what [scan and scroll](https://www.elastic.co/guide/en/elasticsearch/guide/current/scan-scroll.html) really are. So you now have a `ScanService` that could, in principle, be merged with the `ScrollService` (or built on your own just by using the Search service). It's not bad that there are two such services, but they basically do the same thing.

So what is scan-and-scroll? While `search_type=scan` disables sorting (which is costly), `scroll` enables a server-side cursor (if you will) to quickly retrieve documents in batches. Together they are the most effective way to I know of to dump data with the REST API.

I will provide a fix for your use case which will look roughly like this:

```go
// With using SearchSource:
src := elastic.NewSearchSource().
    Query(elastic.NewTermFilter("group.field1", "foo").
    FetchSourceContext(elastic.NewFetchSourceContext(true).Include("group")).
cursor, err := client.Scan("index1").SearchSource(src).Do()
...

// Without SearchSource:
cursor, err := client.Scan("index1").
    Query(elastic.NewTermFilter("group.field1", "foo").
    FetchSourceContext(elastic.NewFetchSourceContext(true).Include("group")).
    Do()
...
```

You can completely rely on `SearchSource` do define your search. It is responsibly for generating the body that is POSTed to the REST API. The `Search` service uses `SearchSource` under the hood; all function calls regarding the query are forwarded to an instance of `SearchSource` (see [here for example](https://github.com/olivere/elastic/blob/master/search.go#L143)). So there is no need to use separate `Query` and `SearchSource` func-calls as you did in your example above.

I could use composition in `Scan` to forward automatically. The problem with anonymous fields though is that you can't get rid of it nicely. Also: What do you do when you want all but 2 fields/methods from `SearchSource` (e.g. because they don't make sense in the `Scan` case)? I'd rather have control over that at the moment. It's just a bit more typing really. :-)

Anyway, I'm a bit busy at the moment. But maybe I can tackle it during the weekend.

**Comment by olivere** [comment]
Do you have a change to look into the [issue-135 branch](https://github.com/olivere/elastic/tree/issue-135) to see if it fits your use case?

**Comment by autochthe** [comment]
This works great!  I am able to fetch partial source documents as I need.

This is completely necessary, but it would be convenient to have a `FetchSourceContext` method on `ScanService`.  I have implemented this in #137.  Either way, this change is good.

**Comment by autochthe** [comment]
Arrrg, I mean to say, adding `FetchSourceContext` to `ScanService` **not** completely necessary.

**Comment by olivere** [comment]
Okay. I think it should be available in v2 as well as v3-unstable. You have `FetchSourceContext` and `FetchSource` of `SearchSource` as convenience functions directly in `ScanService` and `SearchService` now.

I think about merging Scan/Scroll services into a single iterator-like service for 3.0 final though.
