### ISSUE TITLE
Update or allow the `indices_put_template` to use the new `/_index_template` API endpoint

### ISSUE THREAD

**Issue by haywoood** [olivere/elastic#1393]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ x ] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

I expect the `indices_put_template` to use the new https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-template.html#put-index-template-api-request-body `/_index_template/` API endpoint.

### Please describe the actual behavior

The library is routing my request to `/_template` which is creating 'legacy' index templates

**Comment by olivere** [comment]
Thanks for the hint.

I will have to look up if the APIs/endpoints are ~really 100% the same~ compatible. If they're not, I need to create a new service for the new endpoint(s). Otherwise people will use the existing service with 7.x (where x < 8), which has new features that the legacy API doesn't have, then file an issue that it doesn't work.
