### ISSUE TITLE
search Do call makes a POST call, shouldn't it be making a Get call

### ISSUE THREAD

**Issue by RiyaJohn** [olivere/elastic#1403]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v7 (for Elasticsearch 7.x)
[*] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
Since search call is reading data from ES, I was expecting it to make a GET call. Hence I set only read ESHttpGet policy actions when using in AWS.

### Please describe the actual behavior
It is making a POST call, hence require to add write ESHttpPost policy action as well. Else search will written 403 forbidden error

**Comment by olivere** [comment]
It's been a long time since this design decision has been made. IIRC it was due to the fact that at that time some HTTP servers didn't allow a HTTP GET request to have a body, and I think it was Apache HTTPD to misbehave. That is long ago, but changing these things will just break compatibility for no good reason.

So, yeah. You probably need to allow POST as well.

**Comment by RiyaJohn** [comment]
Thank you for the information:)
