### ISSUE TITLE
Cannot unmarshal array when naming filter

### ISSUE THREAD

**Issue by avleen** [olivere/elastic#143]
If you have a named filter, the response from Elasticsearch includes the name of the filter like this:
```
            "matched_queries": [
               "date_filter"
            ]
```

But this breaks with an error:
```
2015/10/08 14:40:48 json: cannot unmarshal array into Go value of type map[string]interface {}
```
```
    MatchedQueries map[string]interface{}         `json:"matched_queries"` // matched queries
```

I'm using `client.Scan()` and finding this. I'm not sure if it happens with other queries, though I expect it should.

**Comment by olivere** [comment]
Do you mind telling me which Elasticsearch version you're using?

**Comment by olivere** [comment]
I looked into the [Java code](https://github.com/elastic/elasticsearch/blob/v1.7.2/src/main/java/org/elasticsearch/search/internal/InternalSearchHit.java#L507) and you are correct: It should be an array of strings, not a map.

It should be fixed by [this commit](https://github.com/olivere/elastic/commit/ae434218769e30e3254d86e65d3d0c9413300900). Thanks for reporting.

I will backport this into elastic.v3 as well.

**Comment by avleen** [comment]
Wow thanks for the speedy response!
