### ISSUE TITLE
Direct access to HTTP response

### ISSUE THREAD

**Issue by atombender** [olivere/elastic#1444]
Background: We're using the client in an application where concurrent memory usage is a significant concern, and queries can return many megabytes of data in some cases. To reduce memory usage and increase pipelining of throughout our query handling, we've developed a solution where we stream the byte stream from Elasticsearch instead of unmarshalling of the entire response into a struct.

This works really well, but we had to use a custom JSON parser to accomplish this, and we also needed direct access to the HTTP response instead of getting a struct back. Unfortunately, the client doesn't permit this; we encountered some roadblocks:

* Every `Do()` method unmarshals the response.
* The client has a `PerformRequest()`, but it reads the entire body and does not return a stream.
* There's no way to ask a client for its configuration so that one can set up a new request
* All the logic to build an HTTP request are buried in the `Do()` methods

We ended up creating a "wrapper client" that contains an `*elastic.Client`, but also carries around with it the URL of the server and some other configuration. Then we use `net/http` to make an HTTP request, bypassing the client altogether. Fortunately, we are able to reuse structs like `elastic.SearchRequest`, but we have to construct the HTTP envelope (e.g. `scroll`) ourselves. We also have to do things like URL construction, logging, status handling, retrying, etc. ourselves.

Here's a snippet from our current logic, greatly simplified:

```go
b, err := search.Body()  // search is a *elastic.SearchRequest we've prepared
if err != nil {
	return err
}

url := baseURL
url.Query = url.Values{"scroll": []string{keepAlive}}

req, err := http.NewRequest(http.MethodPost, url.String(), bytes.NewReader(b))
if err != nil {
	...
}

resp, err := http.DefaultClient.Do(ctx, req)
if err != nil {
	...
}

return newJSONStream(resp.Body)
```

It would be much better if we could do something like:

```go
scroll := client.Scroll().Index(indeXName).KeepAlive(keepAlive) // etc.

resp, err := scroll.DoStream(ctx)  // Returns an *http.Response
if err != nil {
	...
}

return newJSONStream(resp.Body)
```

Or at least something like:

```
resp, err := client.PerformRequest(ctx, elastic.PerformRequestOptions{
	Body: search,
	Params: url.Values{"scroll": []string{keepAlive}},
	Stream: true,  // Signals that body should be returned as a stream
})
if err != nil {
	...
}

return newJSONStream(resp.Body)
```

Thoughts?

**Comment by olivere** [comment]
Thanks for your proposal.

I feel you when it comes to streaming and delayed serialization. Elastic is now 8 years old (first commit on Dec 6, 2012), and one can feel it when looking at the code base. Compatibility was always very high on the list of priorities, which played out okay; on the other hand, I learned a lot over the years and would do some things differently today.

But back to the issue: I'd be willing to add a `DoStream` to selected APIs like Search or Bulk, and maybe even add something like `PerformRequestStream` as well for a more low-level interface.

In the long run, we should probably all switch to using the official library. I've not yet used it personally in a project of mine though. What the official driver is really missing is a set of structs to resemble the request/response structure, and I already have a library that takes those from Elastic and moves them out to be used with the official driver. But it's not yet stable because I didn't have enough time this year to work on it.

So yeah, there's a few followup questions that I have, if you don't mind.

1. What version of ES are you using? When we start working on what you proposed, people start asking that for previous versions of ES/Elastic as well, so we should decide if we want to port it back to Elastic 5.x and 6.x as well.
2. Which APIs do you want to have a `DoStream`? I suppose Search API and Bulk API come to mind. Anything else?
3. Did you check if the official driver gives you access to the HTTP response already in a way that works for you? If so, maybe working on the add-on library for request/response structures would be a better priority.

**Comment by atombender** [comment]
Good point about the official client. We have a largish codebase that uses Elastic, and we've been sufficiently happy with it that we haven't considered moving to the official client. I do see that the new client returns streams, but I think it's really weird that it it apparently has no struct support for returning request responses. I don't understand why, but I don't think we could migrate to the official client without those.

> 1. What version of ES are you using? When we start working on what you proposed, people start asking that for previous versions of ES/Elastic as well, so we should decide if we want to port it back to Elastic 5.x and 6.x as well.

We are slowly migrating to 7.10, but we still have some clusters running 5.6. It's mostly a matter of migrating customer indexes over, nothing to do with the application.

> 2. Which APIs do you want to have a `DoStream`? I suppose Search API and Bulk API come to mind. Anything else?

Only search/scroll. For the bulk API, I've [previously discussed](https://github.com/olivere/elastic/issues/415) streaming the bulk data _to_ Elasticsearch, but it's never been a high priority for us.

> 3. Did you check if the official driver gives you access to the HTTP response already in a way that works for you? If so, maybe working on the add-on library for request/response structures would be a better priority.

Yes, see above.

**Comment by atombender** [comment]
I just did a [quick PR](https://github.com/olivere/elastic/pull/1478) with a proposal. Simpler than I thought it would be, now that `PerformRequest` takes an option struct.
