### ISSUE TITLE
How to do Case Insensitive Sorting?

### ISSUE THREAD

**Issue by dmint007** [olivere/elastic#1462]
How to do Case Insensitive Sorting?

I haven't seen anything on `func (s *ScrollService) Sort()`. 

### Which version of Elastic are you using?

✅ elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

**Comment by olivere** [comment]
It very much depends on the field type among other things. E.g. you could make sure the analyzer downcases the content in an analyzer/filter so that it's stored in ES as lower-case. That's just one example of doing it. Please [refer to the ES documentation for an example](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/analysis-keyword-tokenizer.html).
