### ISSUE TITLE
no Elasticsearch node available - under Linux

### ISSUE THREAD

**Issue by firstrow** [olivere/elastic#147]
Hello. I develop my app under mac.
ElasticSearch: 1.5.2
go: 1.5.1

On dev machine code works well, but on production I've got
"no Elasticsearch node available" raised from:  mustActiveConn() method.
ElasticSearch config files/versions are similar on both machines.

Also curl -X GET 'http://127.0.0.1:9200' returns 200OK response.

I have no ideas how to fix this.

**Comment by olivere** [comment]
Hi! Can you tell me a bit more about your setup? It's most probably an issue with the nodes not being available to elastic, e.g. because they are run in a [Docker container](https://github.com/olivere/elastic/wiki/Docker).

Can you please post the output of `curl 'localhost:9200/_nodes/http?pretty'. This is the first thing that elastic does to retrieve all nodes in a cluster, a process called [sniffing](https://github.com/olivere/elastic/wiki/Sniffing). You can disable sniffing if you have stable IPs, you're just testing or you simply don't want elastic to add and remove nodes automatically for you.

**Comment by firstrow** [comment]
So, i've just sorted out the problem. 
Local config(worked):
network.host: 127.0.0.1

Production config(error):
network.bind_host: 127.0.0.1

So, I've updated my prod config and it worked.
