### ISSUE TITLE
XPackSecurityPutUserResponse.User.Created always false.

### ISSUE THREAD

**Issue by vinhph0906** [olivere/elastic#1474]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[X] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I expected Created=true when create a user and false when update the user.  Like this: https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-user.html

### Please describe the actual behavior
XPackSecurityPutUserResponse.User.Create always false however I create or update the user. 

### Any steps to reproduce the behavior?
Just create a user which XPackSecurityPutUser.

**Comment by olivere** [comment]
Yeah, that looks like a bug. Thanks for reporting.

The `PutUserResponse` [should just be](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-user.html#security-api-put-user-example) ...

```go
type PutUserResponse struct {
  Created bool `json:"created"`
}
```

... but we have [defined it like this](https://github.com/olivere/elastic/blob/release-branch.v7/xpack_security_put_user.go#L207-L215).

That's a quick fix, but I would like to add an integration test so that it won't happen again.
