### ISSUE TITLE
Can we relax the validation in ClusterRerouteService (not a bug)?

### ISSUE THREAD

**Issue by jsjtzyy** [olivere/elastic#1560]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ *] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I was trying to call `RetryFailed` in ClusterRerouteService to retry on failed allocation in ES cluster.  The code is quite simple (see below)
```
_, err := m.Client.ClusterReroute().RetryFailed(true).MasterTimeout(m.MasterTimeout).Do(ctx)
``` 
I expected it to succeed even though there was no request body or commands. 
### Please describe the actual behavior
Got `missing allocate commands or raw body` coming from here: https://github.com/olivere/elastic/blob/b7de00ddfd128672eac82ef8f6e938bcbb6c2cd4/cluster_reroute.go#L195

### Any steps to reproduce the behavior?
I did this on Kibana and succeeded, so I wonder if we can relax the validation to accommodate  simply retry_failed case?
```
POST _cluster/reroute?retry_failed
```

**Comment by olivere** [comment]
Hi! That _does_ work, but I suspect this to be a problem with ES. It probably is a nop, i.e. it doesn't do anything in ES.

The documentation clearly states that the request body is required (see [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/cluster-reroute.html#cluster-reroute-api-request-body)). So I think it's good to warn users if they forgot to add a request body. Otherwise they _think_ everything is OK while it really isn't (because ES just swallowed the error).
