### ISSUE TITLE
Failed to insert bulk data in elastic

### ISSUE THREAD

**Issue by umerm-work** [olivere/elastic#1572]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior
I am trying to insert bulk data. I am not getting any error except for in response property `error : true`  . Here is my code snippet.

```
func BulkInsert(ctx context.Context, products []model.Pt) error {
	Counter++
	// create new bulk processor from client
	bulkProcessor, err := ElasticVar.BulkProcessor().
		Name("Bulk Worker 1").
		Workers(5).
		BulkActions(1000).
		BulkSize(2 << 20).
		FlushInterval(1 * time.Second).
		Stats(true).
		After(after).
		Do(context.Background())
	if err != nil {
		log.Println("NewBulkProcessorService err", err)
		return err
	}
	defer bulkProcessor.Close()
	storeIds := map[string]string{}
	// Enqueue the document
	for _, product := range products {
		if _, ok := storeIds[product.Id]; ok {
			continue
		} else {
			storeIds[product.StoreId] = product.StoreId
		}

		dataJSON, err := json.Marshal(product)
		if err != nil {
			// Look up the failed documents with res.Failed(), and e.g. recommit
			log.Println("elastic marshal failed", err)
			return errors.New("elastic marshal failed")
		}
		bulkProcessor.Add(elastic.NewBulkIndexRequest().
			OpType("index").
			Index(Index).
			Type(Type).
			Id(product.Id).
			Doc(string(dataJSON)))
	}
	stats := bulkProcessor.Stats()
	fmt.Printf("Number of times flush has been invoked: %d\n", stats.Flushed)
	fmt.Printf("Number of times workers committed reqs: %d\n", stats.Committed)
	fmt.Printf("Number of requests indexed            : %d\n", stats.Indexed)
	fmt.Printf("Number of requests reported as created: %d\n", stats.Created)
	fmt.Printf("Number of requests reported as updated: %d\n", stats.Updated)
	fmt.Printf("Number of requests reported as success: %d\n", stats.Succeeded)
	fmt.Printf("Number of requests reported as failed : %d\n", stats.Failed)
	fmt.Printf("\n\n")
	for i, w := range stats.Workers {
		fmt.Printf("Worker %d: Number of requests queued: %d\n", i, w.Queued)
		fmt.Printf("           Last response time       : %v\n", w.LastDuration)
	}
	fmt.Printf(`Inserted Count: %d`, Counter)
	return nil
}

func after(executionID int64, requests []elastic.BulkableRequest, response *elastic.BulkResponse, err error) {
	if err != nil {
		log.Printf("bulk commit failed, err: %v\n", err)
	}
	// do what ever you want in case bulk commit success
	log.Printf("commit response=%v\n", response.Errors)
	log.Printf("commit successfully, len(requests)=%d\n", len(requests))
}
```

In the callback `after` the response. error is true. When I query the data. None of the records is inserted. Please help.

### Please describe the actual behavior
I want to insert a bulk record. 

### Any steps to reproduce the behavior?
Above code

**Comment by olivere** [comment]
There are two recipes for the Bulk API here, one for the [bulk processor](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/bulk_processor/main.go) and one for doing [bulk indexing](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/bulk_insert/bulk_insert.go) yourself.

If you want tight control over the indexing process, do not use the Bulk Processor. Instead, do the bulk indexing yourself. It's not that hard, and you have complete control over the process.

This library simple interacts with Elasticsearch. If ES returns `"errors": true`, this library does so as well. The library doesn't even try to be clever.

As for your specific issue, you should look into the actual errors that ES dumps. It looks like the indexing is somehow wrong, you have hit the high watermark... it could be anything. Try to run the above mentioned recipes and see if they're working. If they are, the problem is somewhere in your code, not the library.
