### ISSUE TITLE
Unclear when error will be returned and when I have to check for error

### ISSUE THREAD

**Issue by mitar** [olivere/elastic#1584]
### Which version of Elastic are you using?

[x] elastic.v7 (for Elasticsearch 7.x)
[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the issue

So when I make some API call, generally of the form of `elastic.Something.Do(ctx)`, I get result and error back. But it is not clear if checking for error is really enough and when it is not. For example, for `CreateIndex` I have to check `Acknowledged`, too. For `Search`, there are `TimedOut`, `TerminatedEarly`, and `Error` fields. Do I have to check them? Or is error returned in those cases when they are set?

**Comment by milesich** [comment]
You should know what to expect when doing an API call. The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/rest-apis.html) can help you. 

**Usually it is enough to check if the error returned is not nil.** 

For `elastic.Get` you could report all returned errors except not found errors with `elastic.IsNotFound(err)` if you want to handle non-existing documents differently.  In `Bulk API` the error returned could be `nil` but there could be errors in the response so should check there too.

It all comes down to what API are you calling. You may also use one of those `elastic.Is*` function to get more info about the error.

**Comment by olivere** [comment]
What @milesich said...

We try to do what Elasticsearch and Go do.

For Go, the response/error pair is described in the standard library [like so](https://pkg.go.dev/net/http#Client.Do):

> An error is returned if caused by client policy (such as CheckRedirect), or failure to speak HTTP (such as a network connectivity problem). A non-2xx status code doesn't cause an error.

For Elasticsearch, we return what Elasticsearch returns. That means that for some cases like e.g. Bulk Index API, Elasticsearch might return `200 OK` while in the response you see `"errors": true` (because some bulk requests succeeded while a few failed).

It is up to you to consider what is an error and what is not. In some scenarios it might be perfectly OK to swallow a few data points, while in others it's absolutely critical to not lose any data.

**Comment by mitar** [comment]
Hm, but In Elastic, non-2xx status codes do return an error, no?

**Comment by olivere** [comment]
You need to define what you mean by "error"?

If you create a HTTP request in Go and the server responds with HTTP status code 400, then there is no error returned (in the Go definition of "error") ([code](https://go.dev/play/p/Xo7E0YEC7BJ)).

```go
resp, err := http.DefaultClient.Get("https://elastic.co/no-such-page")
if err != nil {
  // This line won't be reached
}
defer resp.Body.Close()
if resp.StatusCode == http.StatusNotFound {
  // You will, however, reach this line
}
```

If you instead want the client to return an `error` whenever something might be semantically wrong in terms of Elasticsearch, you won't be able to do that. And it is not desireable anyway, because then the behaviour of Elasticsearch and the library would be off. Sometimes it's not even sure if something is an error to _you_. As I said, that `"errors": true` might be OK for someone.

**Comment by mitar** [comment]
Sorry for confusion. To me it looks like elastic returns non-nil `err` when HTTP status code is 404. At least `Get` returns it (and then you can use `elastic.IsNotFound`). Isn't this breaking already the "A non-2xx status code doesn't cause an error." from standard library. So I was pointing to your quote from the standard library and that it confused me because Elastic seems to diverge from it.

I understand the rest of points raised in this issue and thank you for your patience explaining them to me. They all make sense. You pass thing through from ElasticSearch and that makes sense. But when there is a 404 you do return non-nil `err`.

**Comment by olivere** [comment]
You're correct in that this is a historic exception to the rule. I have to check if this is still the case, but years ago that's how the official clients for other programming languages behaved.

EDIT: typo

**Comment by olivere** [comment]
You can see it mentioned in a comment [here](https://github.com/olivere/elastic/blob/release-branch.v7/client.go#L1306-L1308):

```go
// Optionally, a list of HTTP error codes to ignore can be passed.
// This is necessary for services that expect e.g. HTTP status 404 as a
// valid outcome (Exists, IndicesExists, IndicesTypeExists).
```

**Comment by mitar** [comment]
Is this by any chance documented somewhere and I missed it? So yea, this exactly is my initial confusion I opened the issue with. Thanks.

Maybe a breaking version which would make this more Go-like might be in order?

**Comment by olivere** [comment]
I'm not aware of any specification that describes this. You should probably ask the people at Elastic.

We won't change that as it will most certainly break thousands of working applications.
