### ISSUE TITLE
CreateIndexIfExists

### ISSUE THREAD

**Issue by aanm** [olivere/elastic#159]
Hey, is it possible to have methods that do the "IfExists"? I'm tired on getting `no such index [type=index_not_found_exception]` when I try to insert something on a non-existing index.
Thanks!
P.S. Congrats on the v3 ;-)

**Comment by olivere** [comment]
Seems like a valuable idea. Can you use index templates? It should automatically create indices then IIRC.

**Comment by aanm** [comment]
@olivere I think I can but I will not use them for now. Unfortunately elastic lost support for dots in field names (https://github.com/elastic/elasticsearch/pull/12068) which was something I was really really really using. Now I'll stop using elastic to store a document and start storing "something" encoded on a different way :-(

**Comment by olivere** [comment]
@aanm At second thought, adding these functions might cause a problem. It might make elastic clever instead of dumb. Let me explain.

I want people to use elastic as a library in the sense that users call functions and the library will "do as it's told". If I'll start adding features like this into elastic I will hide certain aspects from users that I don't want to hide. E.g. people could now start to use `CreateIndexIfNotExists` everywhere ("just to be safe") and then complain that elastic will send two queries and/or queries are slow etc. I think it's better for elastic to *not* be clever and try to be (mostly) a 1:1 library for the features/endpoints that Elasticsearch has to offer.

This is also (basically) what the official libraries do: They have a core (which most often only does HTTP requests, load balancing etc.) and a language-specific DSL for end-users.

So if you are really looking for `xxxIfNotExists` features it is very simple to add them to your own project and then use elastic (or even build another layer on top of elastic for that).

```go
package main

import (
	"gopkg.in/olivere/elastic.v2"
)

func main() {
	client, err := elastic.NewClient()
	if err != nil {
		panic(err)
	}
	body := `{
	"mappings":{
		"tweet":{
			"properties":{
				"message":{ "type": "string" }
			}
		}
	}
}`
	err = CreateIndexIfNotExists(client, "testindex", body)
	if err != nil {
		panic(err)
	}
}

func CreateIndexIfNotExists(client *elastic.Client, index string, body string) error {
	exists, err := client.IndexExists(index).Do()
	if err != nil {
		return err
	}
	if exists {
		return nil
	}
	_, err = client.CreateIndex(index).BodyString(body).Do()
	if err != nil {
		return err
	}
	return nil
}
```

I will give my thoughts some more days to consider. Maybe there are good reasons I don't know yet to still open this can of worms. But I hope you understand my line of thinking.

**Comment by aanm** [comment]
@olivere To be honest I was kind impressed that you liked the idea in the first place. Yeah I agree with your point but perhaps you can include a package called `utils` or similar for this kind of tweaks? I don't want you to have more work maintaining another package eheh...

**Comment by olivere** [comment]
@aanm I thought of adding a `contrib`-like repository. But it's hard to share internals between two repositories in Go. So there's actually no plan.
