### ISSUE TITLE
Search with match and aggregation - Port from mongodb

### ISSUE THREAD

**Issue by prsolucoes** [olivere/elastic#165]
Hi,

I dont know where to put this question, but i need solve a problem to my open source project (https://github.com/prsolucoes/logstack) on making a plugin to store/retrieve data from elasticsearch with this client.

To add log it is k, now i need collect data from elasticsearch using aggregation. In mongodb im using:

```
pipe := coll.Pipe([]bson.M{
		bson.M{
			"$match": bson.M{
				"token": token,
			},
		},
		bson.M{
			"$group": bson.M{
				"_id": "$type",
				"count": bson.M{
					"$sum": 1,
				},
			},
		},
		bson.M{
			"$project": bson.M{
				"type": bson.M{
					"$toLower": "$_id",
				},
				"quantity": "$count",
				"_id":      0,
			},
		},
	})
```

1 - Match the field "token" with parameter token
2 - Count and Group by "type" field
3 - Lower case the field "type"

Is possible convert it to elasticsearch with this client? Can anyone help me?

**Comment by olivere** [comment]
@prsolucoes Hi. The two references I recommend is [The Definite Guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html) (a free book on Elasticsearch by two of its authors) and the (rather good) [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html).

If you're unfamiliar with Elasticsearch and you're used to work with databases like MongoDB or SQL-like databases, there's a few things you should know.

First, in contrast to databases, ES is used to deal with human language. It can use [tokenizers and analyzers](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis.html) to find matches, e.g. by default a search for "BOOK" and "book" might yield the same results because the [StandardAnalyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-standard-analyzer.html) (used by default) automatically applies the [lower-case token filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lowercase-tokenfilter.html) when you insert new data. In order to store the "raw" field data, you must specify to *not* analyze the field in the so-called [mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html). A [mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html) is basically what a table schema is in databases (not quite but conceptually). Here's how to specify a field as [not_analyzed](https://www.elastic.co/guide/en/elasticsearch/reference/current/string.html) so that its raw data is stored.

Second, [aggregations](https://www.elastic.co/guide/en/elasticsearch/guide/current/aggregations.html) are very powerful--much better (and much faster) than in e.g. SQL. You can nest them, perform [trend analysis with prediction](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-movavg-aggregation.html#_prediction) and much more. However, to do aggregations on a field, you generally must perform it on the "raw" data. Hence it must be non-analyzed (see above).

Third, ES can be used as a very fast, distributed key/value store. Do look up a key, use a (you got it) "raw" unanalyzed field and perform a [Term query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html) on it. Querying ES is generally done by specifying a set of query functions using the [Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html). Grouping is generally done by [aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html). [Sorting](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_sort_order) and [pagination](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html) can also be done very simply. Lower-casing can be done at run-time (I guess), but you probably would do this at index time.

Once you have some data in an ES index, start querying it with the command-line or a tool like [Sense](https://www.elastic.co/guide/en/sense/current/index.html). After that (if you're working with Go), you'd start to translate the JSON-structured queries into Go code. Refer to the tests in this repository if in doubt--they're basically a huge set of example code.

Anyway, I hope this gives you a first idea. I think you have some reading to do to get the general concepts. But if you're familiar with databases you can get it to work in a few hours time. I would start with the introductory sections in [The Definite Guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html) and look up the details in the documentation.
