### ISSUE TITLE
Question about sending []byte of json to bulk indexer

### ISSUE THREAD

**Issue by jgoodall** [olivere/elastic#169]
I have a byte array of a JSON string that I want to add to a BulkIndexRequest. I think that because it is a byte array and not a string, `elastic` is trying to Marshal it to JSON (https://github.com/olivere/elastic/blob/master/bulk_index_request.go#L152). 

I can convert to a string, but I think this has allocation implications that I would like to avoid. Does it make sense to have the case statement in the `Source` method check for a byte array and handle it like a string?

**Comment by olivere** [comment]
@jgoodall Thanks for reporting. Adding a case switch there would make elastic handle all `[]byte` arrays as strings. I'm not sure this is correct every time. Maybe someone wanted to add an array of numbers instead of a string, and this would now be silently ignored. So I guess the correct way of doing this is to wrap it in a string.

```go
line := string(byteArray)
```

Maybe [`json.RawMessage`](https://golang.org/pkg/encoding/json/#RawMessage) is an alternative for your use case.

But maybe I don't have all the details of your use case.

**Comment by jgoodall** [comment]
Ok, thought adding `[]byte` to case might catch unwanted cases... What I did is what you suggested (`string(byteArray)`), and will look into `json.RawMessage`.
