### ISSUE TITLE
Set Mapping for Index directly during creation

### ISSUE THREAD

**Issue by sundarv85** [olivere/elastic#191]
Hello,

I’m trying to set the mapping for the index directly, instead of its types separately.

From Sense on 2.1 ES, this works

```
PUT /country
{
  "settings": {
    "index": {
      "refresh_interval": "5s"
    }
  },
  "mappings": {
    "states": {
      "_all": {
        "enabled": false 
      },
      "properties": {
        "name": {
          "type": "string",
          "analyzer": "standard"
        }
      }
    },
    "cities": {
      "_all": {
        "enabled": false 
      },
      "_parent": {
        "type": "states",
        "fielddata": {
          "loading": "eager_global_ordinals"
        }
      },
      "properties": {
        "name": {
          "type": "string",
          "analyzer": "standard"
        }
      }
    }
  }
}
```

Of course, `client.PutMapping().Index("country").BodyString(mapping).Do()`, throws the error: `missing required fields: [Type]`

This is because, this is only a mapping creation call, unlike the PUT call. Is there a way to do that - to combine, index creation and setting mapping for all types.

**Comment by olivere** [comment]
@sundarv85 You can do that with [`CreateIndex`](https://github.com/olivere/elastic/blob/release-branch.v3/indices_create.go). Just checked the [Wiki entry](https://github.com/olivere/elastic/wiki/CreateIndex)--it still works with elastic.v3. However, you should probably use either `BodyString(...)` or `BodyJson(...)` instead of `Body(...)`.
