### ISSUE TITLE
Delete By Query - SetParent needed?

### ISSUE THREAD

**Issue by sundarv85** [olivere/elastic#204]
Hello,

I noticed that in delete_by_query.go, there is a Routing() option, but not a Parent().

In some files, such as exists.go, there is both Routing() and Parent().

So, do we need Parent in delete_by_query.go. 

Two more findings:

- When the plugin is not enabled, I’m getting the error 
```
elastic: Error 404 (Not Found)
```

And not `elastic.ErrPluginNotFound` as in `CHANGELOG-3.0.md`

```
Example for Elastic 3.0 (new):

_, err := client.DeleteByQuery().Query(elastic.NewTermQuery("client", "1")).Do()
if err == elastic.ErrPluginNotFound {
	// Delete By Query API is not available
}

```

- When I pass the parent in routing as well, it works. Also, if I pass it in Parent (I added that. See below), it also works. Which is correct? If they are interchangeable, then why do other services like ExistsService support both.

**My changeset**

```
--- a/Godeps/_workspace/src/github.com/olivere/elastic/delete_by_query.go
+++ b/Godeps/_workspace/src/github.com/olivere/elastic/delete_by_query.go
@@ -28,6 +28,7 @@ type DeleteByQueryService struct {
        expandWildcards   string
        replication       string
        routing           string
+       parent            string
        timeout           string
        pretty            bool
        q                 string
@@ -142,6 +143,12 @@ func (s *DeleteByQueryService) Routing(routing string) *DeleteByQueryService {
        return s
 }

+// Parent is the ID of the parent document.
+func (s *DeleteByQueryService) Parent(parent string) *DeleteByQueryService {
+       s.parent = parent
+       return s
+}
+
 // Timeout sets an explicit operation timeout, e.g. "1s" or "10000ms".
 func (s *DeleteByQueryService) Timeout(timeout string) *DeleteByQueryService {
        s.timeout = timeout
@@ -229,6 +236,9 @@ func (s *DeleteByQueryService) Do() (*DeleteByQueryResult, error) {
        if s.routing != "" {
                params.Set("routing", s.routing)
        }
+       if s.parent != "" {
+               params.Set("parent", s.parent)
+       }
        if s.timeout != "" {
                params.Set("timeout", s.timeout)
        }
```

**Comment by sundarv85** [comment]
I see that, the DeleteByQuery fails only when I have not installed the plugin. And since I’m using parent_child, it fails with the error `type=routing_missing_exception`. After I install the plugin, then it doesn't even ask for `routing` or `parent`. I’m confused, why it first thinks it needs routing and when I install the plugin, it doesn’t care about routing, even though I’m passing `term` with `_parent` to be deleted.

**Comment by olivere** [comment]
@sundarv85 AFAIK routing and parent/child are different concepts and serve different purposes. [Routing](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/mapping-routing-field.html) is for "routing" a document to a particular shard in your cluster. If not specified, it uses `_id` or `_parent` (see docs)--maybe that's the reason for your confusion? [Parent/child](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/mapping-parent-field.html) is for relationships between two types of (tightly-bound) documents.

According to [DBQ docs](https://www.elastic.co/guide/en/elasticsearch/plugins/current/delete-by-query-usage.html), there is no parent property. I don't see it in the [Java source](https://github.com/elastic/elasticsearch/blob/master/plugins/delete-by-query/src/main/java/org/elasticsearch/action/deletebyquery/DeleteByQueryRequest.java) as well.

I'll keep the issue open as I still need to double-check the correct error message when DBQ is installed/not installed.

**Comment by olivere** [comment]
You are correct in that DBQ service does not respond with `ErrPluginNotFound`. It responds with a 404.

But TBH I think responding as if the endpoint is missing is the correct response. `ErrPluginNotFound` is a good idea at first sight. But it comes with the burden that you'll now always have to double check if it's an error because some feature might be missing, or it's something wrong with your query. I think elastic should be opaque here and simply return what ES returns, and it shouldn't put any logic into the response. So I think I will change the documentation accordingly.

If an application relies on some plugins, it should probably check those dependencies on startup (via e.g. `HasPlugin` or `SetRequiredPlugins`) other then rely on checking constantly while under load.

Regarding your confusion about DBQ:

The endpoints that DBQ plugin is registering is `DELETE /{index}/{type}/_query` and `DELETE /{index}/_query`. If you don't register DBQ, these will get routed to the Delete API, and `_query` will be interpreted as the `_id` you want to delete. The type you're trying to delete might require a `_parent`, hence the error. It also explains why it 404's: Because there is no document with an identifier of `"_query"`.

When you use parent/child, the `_parent` is used as a routing value to make sure that the parent and its child documents are routed to the same shard. Otherwise it would be hard or even impossible to get acceptable response time when searching.

**Comment by olivere** [comment]
Can we close this?

**Comment by sundarv85** [comment]
@olivere Yes, the issue is solved. Thanks
