### ISSUE TITLE
Error on query for recent indexed document by _id

### ISSUE THREAD

**Issue by secmask** [olivere/elastic#232]
I have a small test here https://play.golang.org/p/v72uBQJ8qW
1. ElasticSearch 2.2.0 (start with default)
2. Elastic 3.0

Reproduce step:
1. Index a document and let ElasticSearch generate id for it.
2. Query the recent inserted document by _id (with TermQuery), for several run, sometime it found, sometime not (use this _id in Sense and it working well)
Is this a bug?

**Comment by olivere** [comment]
Seems like you're hitting refresh limits. Correct?

ES/Lucene are near realtime. You can use Refresh(true) when indexing to persist changes, but that comes with a cost.

See https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-refresh.html and 
https://www.elastic.co/guide/en/elasticsearch/guide/current/near-real-time.html.

**Comment by secmask** [comment]
new version here https://play.golang.org/p/uRVtY38OHI
even I try Refresh option, (and sleep for 5 seconds later) the query still cannot find the document

**Comment by secmask** [comment]
yep, I have missed it. 
Is there any different between use index option Refresh(true) and use an explicit call client.Refresh().Index(..) ? , the later does not work for me.

**Comment by olivere** [comment]
In your examples, you are searching for `id_`, not `_id`. Not sure if you missed that.

Regarding the latter: IIRC `Refresh(true)` is available in some APIs. As the documentation says, it [makes all operations performed since the last refresh available for search](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/indices-refresh.html). No, there's no difference between the two ([read here](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/docs-index_.html#index-refresh)). It's just two roundtrips instead of one.

**Comment by secmask** [comment]
yep, id_ is my mistake, thank you.
