### ISSUE TITLE
Question on index and receive data object

### ISSUE THREAD

**Issue by secmask** [olivere/elastic#234]
I don't know if question here is allow, but I cannot find anywhere else.
My situation is:
I have an object call Message

```
type Message struct{
   Id string `json:"_id"`
   Content string `json:"content"`
}
```
I like to use Id generate by Elastic, then map the "_id" field of document to `Id` of the object when I query later.
Problem is when I create an message object(with Id field is empty string) and index it. the Elastic said Id ("_id") is meta field and should not be here.

So, I use an alternative solution
```
type Message struct{
   Content string `json:"content"`
}
type EsMessage struct{
  Id string `json:"_id"`
  Message
}
```
I use `Message` to create object when Index, and `EsMessage` in receive object like this
```
var msg EsMessage
for _,item := range resp.Each(reflect.TypeOf(msg)){
	if m,ok := item.(EsMessage);ok{
		return &m,nil
	}else{
		return nil,errors.New("LoadMessage: cannot convert to Message")
	}
}
```
But it seem that `Id` field still did not get fill in (other fields is ok). So is there a solution for this?

**Comment by olivere** [comment]
The `_id` field is not part of the source. Source is for your document data, `_id` is metadata. Why do you return it as part of your message?

There are two options I see here.

a) Your ID is not metadata but part of your domain model. Then you could just generate IDs yourself and tell ES to use them. I generally use an `id` field for that and re-use it for e.g. finding documents by id.

b) Your ID is metadata and you want ES to generate it for you. Then it shouldn't be part of your domain model. If you still need the `_id`, you should populate it from the response after searching. To ensure that the ID doesn't get serialized to JSON, use:

```
type Message struct {
  ID string `json:"-"`  // do not serialize to JSON; will be populated after each search
  Content string `json:"content"`
}
```

**Comment by secmask** [comment]
I will follow the first case, the `Id` must be unique for each message, is any guide line how to generate this to avoid conflict?

**Comment by olivere** [comment]
That's what I'm using as well. You could use any algorithm that generates unique numbers. A [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) will do most of the time, but there are many different id generators with various characteristics with regard to space, time, probability of duplicates etc.

You can also generate a domain-specific (unique) identifier, derived from your data model, just like a unique index in a database. This has the advantage that the identifier "speaks" ... you can "see" things by just looking at the id. It also makes updates easier because you can derive the id and just send an update (without a find). However, if you want to use the id e.g. as part of the URL in a REST API, you might get into encoding issues.

It all depends on your use case.
