### ISSUE TITLE
Unable to connect to node which is not at the base URL.

### ISSUE THREAD

**Issue by shendaras** [olivere/elastic#243]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
I am able to connect to an elasticsearch node running at http://localhost/elastic/

### Please describe the actual behavior
Currently, the path is stripped from the URL as part of canonicalize. This causes requests to go to http://localhost/ directly.

### Any steps to reproduce the behavior?
Create an elasticsearch node and have it accessible via a URL with a path.

**Comment by olivere** [comment]
Looked into the official clients. They support this as well. Fixed in [this commit](https://github.com/olivere/elastic/commit/df416f02670ed201b1d04e9b198e14bc1f4c9478), also [backported to v2](https://github.com/olivere/elastic/commit/e713be938499714ee063069b868040d39c96cffd).

Thanks for being a contributor.
