### ISSUE TITLE
Memory optimalization

### ISSUE THREAD

**Issue by r--w** [olivere/elastic#248]
Hi,
Thanks for this software it's awesome, but after we switched  we found that number of GC increased. Simple profiling:
```
go tool pprof -alloc_objects http://production-23:6060/debug/pprof/heap
```
Shows that the problem is with estimateSizeInBytes method:

![estimateSizeInBytes](http://i.imgur.com/6tM57X9.png)

So my suggestion is that you can simple use len function here (without casting to []byte): https://github.com/olivere/elastic/blob/release-branch.v3/bulk.go#L82
As described in documentation 

> The length of a string s (its size in bytes) can be discovered using the built-in function len

And instead of strings.Join method from https://github.com/olivere/elastic/blob/release-branch.v3/bulk_index_request.go#L96 bytes.Buffer can be used as described here: http://herman.asia/efficient-string-concatenation-in-go

**Comment by olivere** [comment]
Thanks for reporting. I agree, this is rather inefficient. While squeezing out the last bits and pieces is not the primary goal of Elastic, this is low hanging fruit, so I'll fix it as soon as I find the time.

**Comment by olivere** [comment]
Just for reference:

Old version:

```go
func (s *BulkService) estimateSizeInBytes(r BulkableRequest) int64 {
	// +1 for the \n
	return int64(1 + len([]byte(r.String())))
}
```
```sh
$ go test -bench=BulkEstimat -test.benchmem
PASS
BenchmarkBulkEstimatedSizeInBytes-4	  500000	      3852 ns/op	    1576 B/op	      30 allocs/op
```

New version:

```go
func (s *BulkService) estimateSizeInBytes(r BulkableRequest) int64 {
	// +1 for the \n
	return int64(1 + len(r.String()))
}
```
```sh
$ go test -bench=BulkEstimat -test.benchmem
PASS
BenchmarkBulkEstimatedSizeInBytes-4	  500000	      3722 ns/op	    1512 B/op	      29 allocs/op
```

... which is only marginally better (not what I was expecting).

Same with string concatenation:

Before:

```go
func (r *BulkDeleteRequest) String() string {
	lines, err := r.Source()
	if err == nil {
		return strings.Join(lines, "\n")
	}
	return fmt.Sprintf("error: %v", err)
}
```
```sh
$ go test -bench=BulkDeleteRequestSerialization -test.benchmem
PASS
BenchmarkBulkDeleteRequestSerialization-4	  500000	      3695 ns/op	    1512 B/op	      29 allocs/op
```

After:

```go
func (r *BulkDeleteRequest) String() string {
	lines, err := r.Source()
	if err == nil {
		var buf bytes.Buffer
		for _, line := range lines {
			buf.WriteString(line)
			buf.WriteString("\n")
		}
		return buf.String()
	}
	return fmt.Sprintf("error: %v", err)
}
```
```sh
$ go test -bench=BulkDeleteRequestSerialization -test.benchmem
PASS
BenchmarkBulkDeleteRequestSerialization-4	  300000	      3788 ns/op	    1688 B/op	      31 allocs/op
```

... which is actually worse than before (and less readable).

We can probably do much better here, but it looks like it's not as low-hanging fruit as I thought initially. I changed the string-length issue because casting to `[]byte` is probably not necessary, but otherwise I left the code as is. I [committed the benchmarks](https://github.com/olivere/elastic/commit/9169c78a9b93239439b4cf16524c047b4ea207ff) so you can try for yourself.  Just run `go test -bench=. -test.benchmem`.

Maybe you can have a look at it.

I will delay bigger changes until we have a clear picture.

**Comment by r--w** [comment]
Wow, thanks, that's impressive:)
We are commiting more than 500M docs per day, so for sure i'll take a closer look at this issue soon.

**Comment by r--w** [comment]
Just one more suggestion, maybe the simplest way would be an option to add more than one document at once, then the estimateSizeInBytes method would be called once after all docs are added to the requests slice?

**Comment by olivere** [comment]
500M documents is quite large. We do about 50M on a good day. Thanks for sharing. Do you use `BulkProcessor`, or do you implement the bulking via `BulkService`?

Re: you proposal. Yes, adding more than 1 document is one way to improve. I personally was looking for a way to deserialize only once (the `String()` method is called way too often, me thinks). But don't expect quick fixes here because I see stability to be the highest priority at this point in time. I will probably open up a branch for the work of improving this. It'll probably take a while.

**Comment by r--w** [comment]
We are using BulkService.
Please check https://github.com/olivere/elastic/pull/250
