### ISSUE TITLE
Cannot set parameter for Significant Terms Aggregation like "gnd" or "chi_square"?

### ISSUE THREAD

**Issue by mosasiru** [olivere/elastic#258]
[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)

Significant Terms Aggregation has parameter like "gnd" for tuning.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-significantterms-aggregation.html#_parameters_6

This library doesn't seems to be able to set these parameters.
Is there any way to set?

**Comment by olivere** [comment]
I haven't implemented this currently. But they're coming. It's hard to stay on top of ES features because they're not published in advance and I don't have enough time to keep on reading the ES issues/meta-issues.

So I keep implementing stuff as required. I will keep this issue open and will report progress here, but it'll probably take me a few days.

**Comment by mosasiru** [comment]
I realized. thank you.

**Comment by olivere** [comment]
[This commit](https://github.com/olivere/elastic/commit/0aac3269f8377d75ae97dae319e248b67d11edd0) adds significance heuristics to the significant terms aggregation. It will be released to elastic.v3 later this weekend.

**Comment by mosasiru** [comment]
thank you for speedy implement!!
