### ISSUE TITLE
about driver router when one instance drop off the cluster

### ISSUE THREAD

**Issue by ishare** [olivere/elastic#270]
### Which version of Elastic are you using?
[√] elastic.v2 (for Elasticsearch 1.x)

For example, 3 instances in the cluster, with 1 replica. When one instance drop off the cluster, but still alive. The another two still hold the whole data. Can the driver router to the two instances, not router to the standalone instance?

**Comment by olivere** [comment]
How Elastic picks the nodes it will connect to is described in the Wiki under [Sniffing](https://github.com/olivere/elastic/wiki/Sniffing) and [Healthchecks](https://github.com/olivere/elastic/wiki/Healthcheck).

In a nutshell, Elastic will (by default) find all the nodes in the cluster at startup. It will then use round-robin to connect to these nodes. If one node has connection problems, it is marked as "dead" and will not be used any more (until re-enabled by a healthcheck). Periodically, Elastic repeats the check done at startup to e.g. pick up new nodes or re-enable nodes previously marked as "dead".

However, if your cluster is "bad" in the sense that it is split in two halfs, you get into a "split brain" situation. Then your cluster is at risk because two nodes might think they are master nodes, and your cluster is at risk at losing data. If the two nodes are still accessible by Elastic, they will be used, and Elastic cannot do anything to prevent this. You should take care that your cluster is as resilient as possible against to those cases, e.g. by [configuring the # of minimum master nodes](https://www.elastic.co/guide/en/elasticsearch/guide/current/important-configuration-changes.html#_minimum_master_nodes).

Does this answer your question?

**Comment by ishare** [comment]
Thanks for your explain, I'll try the `minimum_master_nodes`. So the driver will not connect to the standalone instance if it is not a master?

**Comment by olivere** [comment]
No. Elastic will connect to any node it has received in the last sniffing/healthcheck process in a round-robin fashion.

**Comment by olivere** [comment]
Can we close this?

**Comment by ishare** [comment]
yeah, thanks very much.
