### ISSUE TITLE
why are urls canonicalized?

### ISSUE THREAD

**Issue by saxsir** [olivere/elastic#278]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
Why are urls canonicalized?
On line https://github.com/olivere/elastic/blob/v3.0.34/client.go#L219

I hosted elasticsearch node on sub directory (e.g. `http://hoge.com/es/`
I cann't connect my elasticsearch because of this line.

```
$ curl http://hoge.com/es/
{
  "name" : "hoge-es",
  "cluster_name" : "hoge01",
  "version" : {
    "number" : "2.2.0",
    "build_hash" : "8ff36d139e16f8720f2947ef62c8167a888992fe",
    "build_timestamp" : "2016-01-27T13:32:39Z",
    "build_snapshot" : false,
    "lucene_version" : "5.4.1"
  },
  "tagline" : "You Know, for Search"
}
```

```
$ ./es-connect-test -host=http://hoge.com/es/
no Elasticsearch node available 
```  

### Please describe the actual behavior
* elastic.Client should not canonicalize urls..

**Comment by olivere** [comment]
I'm on vacation this week, so sorry for the late reply.

Your URL should work fine. See the canonicalize_test.go file for tests. Maybe "sniffing" is the problem here. See the Wiki for a description of the startup process.

Canonicalization is done to normalize URLs, e.g. remove trailing slashes. I could remove it but then I'd have to respond to issues that have to do with malformed URLs ;-)

**Comment by saxsir** [comment]
Thank you for a reply.

> Your URL should work fine. See the canonicalize_test.go file for tests. 

You're right. I'm so sorry, my local copy was not the latest version...
Now, it's working :)  (Updated local repository now)

> malformed URLs
I got it, thanks.
