### ISSUE TITLE
Deprecated APIs

### ISSUE THREAD

**Issue by vsiv** [olivere/elastic#289]
@olivere Do you think it make sense to warn developers of using deprecated apis via logging (might need to introduce a dev/prod mode to turn these off). For example, count search type is now deprecated as of 2.0. It might make it easier for dev's this way to stay away from deprecated apis. 

Just a thought. Feel free to close this, as its a bit out there 🎱 

V
PS. [Quick search link for deprecated apis](https://www.elastic.co/search?q=deprecated&section=Docs%2FElasticsearch%2FReference%2F2.3&cpreferrer=https%3A%2F%2Fwww.google.co.in%2F&cpreferrer__c=https%3A%2F%2Fwww.google.co.in%2F&cpreferer=https%3A%2F%2Fwww.google.co.in%2F&cpreferer__c=https%3A%2F%2Fwww.google.co.in%2F)

**Comment by olivere** [comment]
Hmm... sounds like a good idea until you try to implement it. How do I figure out if someone uses `search_type`? I would probably need to inspect parameters, right? Do you really want to go down that route? Besides, I think that most of the warnings would be because of Elastic using deprecated APIs and/or parameters. :-)

It's really time consuming to stay on top of the large API surface. You could figure out the top-level issues on the Elasticsearch GitHub repository that track these changes. But it's a full-time job I suppose, and I currently don't have the time to do that TBH.

But thanks for your idea. Maybe we can find a simple way to implement that. Will keep it open and add as "enhancement" to let it sink in.

**Comment by vsiv** [comment]
@olivere agree! another option is to close this for now, until more users request it.

**Comment by olivere** [comment]
I think I'll close this for now. Maybe ES will return something from the server-side in future.

Still, thanks for the idea!
