### ISSUE TITLE
Getting Started example doesn't work no mapping for [user] in order to sort on

### ISSUE THREAD

**Issue by nicolaifsf** [olivere/elastic#294]
[ ] elastic.v2 (for Elasticsearch 1.x)
[x] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
Expected behavior is that it returns search query prettified and sorted

### Please describe the actual behavior
panic: elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]

**Comment by olivere** [comment]
I'm didn't get that error. The getting started is not meant as a complete, working example. It's for getting a "feel" of working with Elastic. But, you're right in that it should provide such an example.

I've added a link to a [complete working example](https://gist.github.com/olivere/114347ff9d9cfdca7bdc0ecea8b82263) in the README and fixed a potential issue one could fall into (forcing a Refresh when indexing so that the search will always find the newly added document).

Thanks for reporting.
