### ISSUE TITLE
elastic should trace the response even http status code is not 2xx

### ISSUE THREAD

**Issue by Jack47** [olivere/elastic#297]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[X] elastic.v3 (for Elasticsearch 2.x)
### Please describe the expected behavior

elastic should trace the response even the http status code is not 2xx. 
### Please describe the actual behavior

I want to find specific doc by it's id, this doc doesn't exist in ES, then elastic returned an error with status code 401. I set trace log for elastic and try to figure out what happened, but I can't see the corresponding http response in trace log.
### Any steps to reproduce the behavior?

Try to find an not exist doc by it's id

**Comment by olivere** [comment]
I'll investigate if I can change `Client.PerformRequest` accordingly. Thanks for reporting.

**Comment by freb** [comment]
I believe the issue I'm having is the same. I had a scroll request that would return an error on:

    results, err := scroll.Do(ctx)

Which I then use to panic. The panic takes place because the response is a `400`, but I only get a portion of the actual response that is included in `err` and not the full trace as configured on the client. This is all I see:

    panic: elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]

I ended up using the trace output of the request to send a curl request. It's response included the additional detail I needed:

    "reason":"No mapping found for [flow.] in order to sort on"

Adding `reason` to the error or tracing the raw response before the error is returned would help.

**Comment by olivere** [comment]
@freb Yes, fixing the tracing is an open issue, but it's fixed soon by #553. You can get access to all error details that ES returns by type checking on [`Error`](https://github.com/olivere/elastic/blob/release-branch.v5/errors.go#L63).

**Comment by freb** [comment]
Sorry! I didn't see the separate issue. Good to know about type checking `Error`, I hadn't thought of that.

Anyway, thanks for the awesome library. I'm enjoying it much more than official Python library.

**Comment by olivere** [comment]
Closing for it is too old. If you still see this as a problem, please file a new issue and link back to this one. Thanks.
