### ISSUE TITLE
Use backoff pkg in PerformRequest

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#298]
Currently, `Client.PerformRequest` uses a simple exponential backoff. We now have a "real" `backoff` package which we could use instead.

**Comment by atombender** [comment]
Related things I'd love to have:

* Retry + backoff on certain HTTP errors such as 502, 503 and 429 ("Too Many Requests"), which it looks like the current code doesn't do.
* Same on system errors such as `syscall.ECONNREFUSED` (not sure if this is done today, but it doesn't look like it).
* A pluggable interface for classifying the error. Something like `IsRetriable(err) bool`, which would let the user plug in their own classification. For example, if you don't want to handle 429, I could just plug in my own classifier that did.
* A pluggable interface for the retrier. So instead of `SetMaxRetries` or whatever, you could do: `SetRetrier(MyRetrier{Type: Exponential, MaxBackoff: 10, MaxRetries: 100})` or whatever, in order to do something completely custom.

Semi-related:

* An interface for the underlying HTTP client. This would allow mocking ES. Currently we use `httptest.Server`, which is fine for some things, but heavyweight, and doesn't integrate with Testify's mock system.

**Comment by olivere** [comment]
@atombender Yes, all valid use cases.

Re "`syscall.ECONNREFUSED`": That interesting. I've been running Elastic and ES in production for close to 4 years now and I've never seen that error. When does that happen?

Re "interface to the underlying HTTP client": Maybe working with a custom `http.RoundTripper` already simplifies some of your use cases (see e.g. [here](https://github.com/olivere/elastic/blob/release-branch.v5/client_test.go#L847-L881)).

**Comment by atombender** [comment]
`ECONNREFUSED` would occur if Elasticsearch is not running, so it's completely feasible. As is `ECONNRESET`, `EHOSTDOWN` and `EHOSTUNREACH`, when you have small blips in the network, or genuine network unavailability.

I'm not familiar with `RoundTripper` — if that's sufficient then it's moot, of course. Will check it out.

**Comment by olivere** [comment]
@atombender There's a WIP in the [`retrier` branch](https://github.com/olivere/elastic/commit/9e24f645b80a8bdce4c60203f807b2b3ceb39490). I think it would make retries much more customizable. However I don't like the factory method that generates the `Retrier` implementation for every HTTP request. Maybe there's a better way.

If you have some spare time, I'd be happy if you could skim over it.

**Comment by olivere** [comment]
You should have a way to intercept HTTP failures via `Retrier` now (see [a855324](https://github.com/olivere/elastic/commit/a85532499f01f2c7eccb34ec7c850d2c01134319) for implementation). I'm about to document the `Retrier` in the wiki later.

Let me know if this doesn't fix your use cases.

**Comment by atombender** [comment]
Sorry about not replying earlier; been swamped. This looks really good, thanks.

**Comment by olivere** [comment]
No problem. Same here. Project is moving slowly, but it's still moving forward. :-)

**Comment by nickcarenza** [comment]
Are 502s and 504s supposed to be caught by the retrier? I added this to my client config but 502s still seem to be bubbling up immediately.

```go
elastic.SetRetrier(elastic.NewBackoffRetrier(elastic.NewExponentialBackoff(1*time.Minute, 1*time.Hour)))
```

I could also be using it wrong.

**Comment by olivere** [comment]
@nickcarenza By default, Elastic sets up no retries and doesn't handle errors. If you configure your own retrier, you can define which errors kick off a retry. See [the Wiki](https://github.com/olivere/elastic/wiki/Retrier-and-Backoff) for an example.
