### ISSUE TITLE
PingService only allows ping of defaultUrl

### ISSUE THREAD

**Issue by rnix** [olivere/elastic#36]
If the server isn't on the localhost, [PingService](https://github.com/olivere/elastic/blob/190f272208dac97580821322db02f4c3e63f2042/ping.go#L46) will not be able to access it even if the Client is configured with a different URL.

**Comment by olivere** [comment]
That's just the default URL. You can specify a different URL via [URL(...)](https://github.com/olivere/elastic/blob/master/ping.go#L53).

**Comment by rnix** [comment]
Thanks. Sorry. Only, it's a little confusing when initializing the ping from a Client and PingService not using the URL of the client.

**Comment by olivere** [comment]
Yes, I see. The problem is: You can have a client that connects to more than one ES server. So which URL do you use then?

I see the PingService as a more general service to check ES servers, not only those defined in the client. I could probably enforce setting a URL so that there is less confusion. I'm thinking about it... Thanks for bringing this up.

**Comment by rnix** [comment]
Yea, I noticed that while looking through the source which is why I filed this issue instead of providing a pull request.
In reality, all I care about is the info response from ping so if that where available from the Client, it might mean I don't need the PingService (and since NewRequest pings the URLs internally,)
