### ISSUE TITLE
Cannot use Scan or Scroll with raw request body

### ISSUE THREAD

**Issue by akotlar** [olivere/elastic#366]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[X ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
We should be able to configure the body of the request from a valid JSON string, or at least a valid map[string]interface{}

### Please describe the actual behavior
There is currently no way to do this.

### Any steps to reproduce the behavior?
This is a fundamental API choice. To reproduce it, try to find a way to search from raw request body. There is no API method for this. SearchService has one, using a workaround that relies on a "source" attribute, which is distinct from its "searchSource" attribute, and is solely used to allow people to work around the SearchSource limitation.

I've spent enough time with the source code to understand that several core modules force the use of the DSL, such as Sort, SearchSource, etc. There is no easy way to rework things to truly support raw queries. From my perspective, this is a tremendous opportunity to improve the utility of this library. The DSL should be completely optional.

I've begun updating the library, and will invest the necessary time if @olivere supports this idea.

Feedback on the proposal is welcome!

**Comment by olivere** [comment]
Without knowing, you are actually touching quite a few different topics in this issue. First of all, I'm not negative on your proposal. I'm just asking to think through the choices before blaming the library of not supporting something that should be "the most basic thing that actually has to work."

First of all, the vast majority of the code in Elastic is due to the DSL. This is where I started, and this is still its core functionality. There were similar requests asking for Elastic to work as a kind of proxy for the responses from Elasticsearch. You may not like it, but this is not its purpose.

Second, if you ask for a feature that accepts something serializable as the body of a request to send it to Elasticsearch: Why not use `net/http` directly? Seriously. It's [not that hard](https://gist.github.com/olivere/478060604604514c163a5bed5cd2339c). If you want to scroll and pass just the query (and set other stuff via the DSL): [You can do that too](https://gist.github.com/olivere/eb0cea18708fdeb9ce04783a04378974).

Third, if you want the services to accept "something" and then change properties via the DSL, this is going to be a lot of work. Setters like `Source(...)` or `Body...(...)` (yes, somewhat confusing) are there to enable callers to specify the body of the request. But they are all-or-nothing. If you go that way, you're on your own: You cannot use the DSL any more. Elastic will never contain a parser for ES syntax. If you think it can do that, you're underestimating the size of the Elasticsearch API.

Fourth, I really want a stable API. The Elastic API is definitely not be the best approach and may even not be idiomatic Go code. That is because in 2012 there simply was no best practices for idiomatic Go code. Some people even blame that Elastic choose to do client-side load-balancing and that it's a bad thing altogether. What they are people is that that's the approach all official Elasticsearch client have gone since 2012, and Elastic wanted to be a good citizen. Long story short, if you want to change major parts of the library, you have to do that in a way that doesn't break compatibility with existing code.

Fifth, there is probably a place for an alternative light version of Elastic. I have not published the code yet, but I've created the basics of a more modern client with an orthogonal approach towards DSL, interacting with ES, load-balancing etc. But then again, I don't see much value in publishing that code--as it's just asking for confusion--and I definitely don't have the time to support two different libraries for the same purpose.

Sixth, if you want to change `SearchSource`, you have to be aware that it's used by many different services: MultiSearch, Reindexing etc. Its definitely not for search only.

Seventh, `ScanService` is deprecated. There is no `ScanService` any more in Elastic v5. It was an error to have both a `ScanService` and a `ScrollService`.

Last but not least I wrote this library because I needed it for myself and I couldn't find anything suitable at that time. Its my way of paying back for the vast amount of Open Source projects I've been using throughout my professional career. I'm actually surprised day after day that so many other people think it is good enough to use it in their own applications.

Again: I'm not criticizing your proposal. I think it's a good idea to make simple things simple and complex things possible. However, I also think that what you're after is not going to be a simple change (or at least I cannot see it) and that you're probably facing some problems you might not see now.

But who knows. I might be surprised. Go ahead and "show me the code" (as Linus says). :-)

**Comment by akotlar** [comment]
@olivere, first I hope that you read my (comment)[https://github.com/olivere/elastic/issues/286#issuecomment-250208009] about my belief that the library is excellent. It certainly seems to be the most complete go library, and it's unfortunate that Elasticsearch does not maintain an official one. I suppose this is one reason your library has grown to prominence, in addition to its independent merits.

Regarding your points:

1. Good to know. Purpose of a library is probably not singular, once the project is relied upon by many people, whether or not a feature should be included is a reflection of the needs of the community. Mine is a single data point, and may not count. There have been several issues similar to this one, for what that's worth.

2. Because it's a pain/re-inventing the wheel, and I don't want to lose the convenience functions this library provides altogether.

3. Yes, we agree on this, that is my impression as well.

4. Stable APIs are important! Agreed.

5. Probably not needed. Given that ultimately a request body is passed to PerformQuery, this seems to be overkill.

6. Agreed, again.

7. Yes I know. Unfortunately, as you've noted yourself, at the moment the ScrollService is somewhat more limited than the ScanService. I did my research before choosing ScanService.

Thank you for making the library. My aim is not to attack your choices. It's clear that you made a particular decision. In my use case it is limiting, and I want to help reduce that limitation, because I think it may help other people, and because integrating it into the main package means a greater chance that the code that I write that will rely on it isn't going to be outdated as quickly.

Would you support a more limited change for now? Simply providing a Source function for ScanService ( I could make one for SearchService as well ), and modifying the Do() function to change the check on searchSource.hasSort() to one that encompasses a body set by Source().

**Comment by olivere** [comment]
Yes. The `ScanService` comment is outdated. There's no easy way to rephrase things recommended earlier.

And yes: I'd be happy to have `Source` or something like that in `ScanService`/`ScrollService` (and that's rather easy to implement). Please see my code review.

**Comment by olivere** [comment]
3.0.55 has been published. It contains a `Body` method for `Scroll` and `Scan`.
