### ISSUE TITLE
[Question]Can trace log only request log?

### ISSUE THREAD

**Issue by jinleileiking** [olivere/elastic#375]
Can only trace request log ? the response log is too big. hard to debug.

**Comment by olivere** [comment]
Unfortunately, that's not possible at the moment.

As a workaround, you could try to wrap `elastic.Logger` and [implement a kind of logger](https://github.com/olivere/elastic/wiki/Logging) so that it only writes the trace if it "looks like" a request, not a response. Not very nice, but e.g. responses should always have a prefix of something like `"HTTP/1.1"`.

**Comment by olivere** [comment]
An alternative is to disable the `elastic.Logger` for trace logging, and instead use a custom `http.RoundTripper` as [described here](https://github.com/olivere/elastic/wiki/HttpTransport). You have complete control over `*http.Request` and `*http.Response` then.

**Comment by jinleileiking** [comment]
Thanks!
