### ISSUE TITLE
mismatch in the example and actual implementation

### ISSUE THREAD

**Issue by kamorahul** [olivere/elastic#412]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[x] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
search

### Please describe the actual behavior
 cannot use &termQuery (type **elastic.TermQuery) as type elastic.Query in argument to client.Search().Index("search").Query:
	**elastic.TermQuery does not implement elastic.Query (missing Source method)

### Any steps to reproduce the behavior?

 // Search with a term query
  termQuery := elastic.NewTermQuery("user", "olivere")
  searchResult, err := client.Search().
    Index("twitter").   // search in index "twitter"
    Query(&termQuery).  // specify the query
    Sort("user", true). // sort by "user" field, ascending
    From(0).Size(10).   // take documents 0-9
    Pretty(true).       // pretty print request and response JSON
    Do()                // execute
  if err != nil {
    // Handle error
    panic(err)
  }

**Comment by olivere** [comment]
Where did you see the above snippet?

It is valid as of Elastic v2, but should cause the compile time error for Elastic v3 and v5.

**Comment by kas240sx89** [comment]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?
[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

*** https://godoc.org/gopkg.in/olivere/elastic.v5 ***

exampe should show a working search query

### Please describe the actual behavior

Search by TermQuery fails:

// Search with a term query
termQuery := elastic.NewTermQuery("user", "olivere")
searchResult, err := client.Search().
    Index("twitter").        // search in index "twitter"
    Query(termQuery).        // specify the query
    Sort("user", true).      // sort by "user" field, ascending
    From(0).Size(10).        // take documents 0-9
    Pretty(true).            // pretty print request and response JSON
    Do(context.Background()) // execute
if err != nil {
    // Handle error
    panic(err)
}

Results in:
Elasticsearch returned with code 200 and version 5.1.1Elasticsearch version 5.1.1
Indexed tweet 1 to index twitter, type tweet
Indexed tweet 2 to index twitter, type tweet
Got document 1 in version 859531528472 from index twitter, type tweet
elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]

goroutine 1 [running]:
panic(0x8b4980, 0xc82000a1a0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.main()
	/home/#####/go/src/testenv/elasticSearch/main.go:128 +0x3857
exit status 2


### Any steps to reproduce the behavior?
run the example code via go run with elastic search in a docker container

**Comment by olivere** [comment]
@kas240sx89 Fixed the example. Thanks.

**Comment by olivere** [comment]
@kamorahul May I ask where you found the example?

This line:

```
Query(&termQuery). // specify the query
```

... is correct for Elastic.v2, but not for v3 and v5. So either you a) looked into the documentation for a different version, or b) I haven't yet found the page where you got the example from.

I'll close this now as I think it's a) not b). But if it's b), just let me know and I'll fix it.

**Comment by rythmkraze** [comment]
@olivere That example likely came from [here](http://olivere.github.io/elastic/)

**Comment by olivere** [comment]
@rythmkraze Yep. Fixed the example there as well.
