### ISSUE TITLE
Streaming bulk requests

### ISSUE THREAD

**Issue by atombender** [olivere/elastic#415]
We need to stream documents to Elasticsearch for two reasons:

* Honour Elasticsearch's `http.max_content_length` setting. When the size of the bulk request reaches that size, we need to commit it.
* Pipeline all the things to avoid excessive RAM issue. We have tons of documents as Go structs. By marshaling everything into a string buffer first, we end up with 2x the size of RAM needed during the request. Rather than collect all the data up front and _then_ encode and _then_ send it, we'd like to start a dedicated connection, stream the data, and sign off on it.

However, I noticed that the bulk service doesn't support streaming: It receives a bunch of requests and then writes them all to a buffer before sending the buffer to ES. I also noticed that I can't sidestep this as the client only exposes a non-streaming `PerformRequest` that takes the full body.

(Note: We use `BulkService` rather than `BulkProcessor` as we need fine-grained control over the inner mechanics of bulk building, including distributing load to multiple workers, retrying and so on.)

The only way I can fix this right now is by using `net/http` directly, but I'd love to have this built into this library. Thoughts?

**Comment by atombender** [comment]
Re interface, I think it would be very similar to the current `BulkService`, except it would need a dedicated client internally (unless HTTP/2, which could share the same connection), and instead of `Do()` you would have something like `End()`:

```go
type Iterator {
  NextDocument() (*Document, error)
}

func streamDocuments(iter Iterator) error {
  bulk := client.StreamingBulk().MaxSize(5 * 1024 * 1024)
  for {
    err, doc := iter.NextDocument()
    if err == io.EOF {
      break
    }
    if err != nil {
      return err
    }

    req := elastic.NewBulkIndexRequest().
      OpType("index").
      Index("myIndex").
      Id(doc.ID).
      Type(doc.Type).
      Doc(doc.Content).
      Version(doc.Version)

    err = bulk.Write(req)
    if err == elastic.SizeExceeded {
      err = bulk.End()
      if err != nil {
        return err
      }
      err = bulk.Write(req)
    }
    if err != nil {
      return err
    }
  }
}
```

Note the error handling. The client doesn't know the size of the request, so the only logical choice is for it to not write anything if the data would exceed the maximum, and force the caller to end the bulk, then continue writing to it (which would start a new streaming HTTP request).

**Comment by olivere** [comment]
For self-reference: The official Python client has a `streaming_bulk` helper: [Source](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/__init__.py#L136).

**Comment by stereosteve** [comment]
@olivere FWIW the python example does not actually do any request string at the HTTP level... it is more akin to the `bulk_processor` in that it accumulates actions and performs a request when they reach `chunk_size` or `max_chunk_bytes`.  [Here](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/helpers/__init__.py#L87) it builds a large string for the chunk actions and performs as one request.

[this 2014 comment](http://elasticsearch-users.115913.n3.nabble.com/Does-the-server-support-streaming-td4047245.html#a4050758) seems to confirm that's the case.  He claims that elastic doesn't support HTTP streaming, but maybe that has changed in the time since.

Also, while it does reduce memory requirements for go client, elastic server would potentially have to deal with more slower connections streaming data instead of getting large bulk requests in "one go".  [This page](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/docs-bulk.html) has the quote `If using the HTTP API, make sure that the client does not send HTTP chunks, as this will slow things down.` tho I'm not sure that has been updated for 5.x

@atombender do you know if elastic 5.x supports streaming HTTP on bulk endpoint?  Does it enable faster indexing, or is your interest more in reducing memory requirements for the go client?

**Comment by atombender** [comment]
@stereosteve This is purely about pipelining, which reduces memory and increases concurrency.

I don't know the details of what ES does on its end, but I would be surprised if it doesn't just stream each "frame" (metadata + content) into the index as it receives it. For example, I don't think it does any validation before it makes the changes; so if you refer to a non-existent index in the middle of a bulk, the preceding items will be processed anyway. That's my understanding, anyway.
