### ISSUE TITLE
Combine a filtered query with an average aggregate

### ISSUE THREAD

**Issue by andrejvanderzee** [olivere/elastic#423]
### Which version of Elastic are you using?

[ X] elastic.v2 (for Elasticsearch 1.x)

How can we combine a filtered query with an average aggregate like this:

```
{
	"query": {
		"filtered": {
			"query": {
				"query_string": {
					"query": "env:dev AND metricType:total",
					"analyze_wildcard": true
				}
			},
			"filter": {
				"bool": {
					"must": [{
						"range": {
							"timestamp": {
								"gte": 1481748200544,
								"lte": 1481750000544,
								"format": "epoch_millis"
							}
						}
					}],
					"must_not": []
				}
			}
		}
	},
	"size": 0,
	"aggs": {
		"1": {
			"avg": {
				"field": "available"
			}
		}
	}
}
```

**Comment by olivere** [comment]
If you need examples of the different filters, queries, and aggregations, use the tests.

E.g. here are the tests for [`Avg` aggregation](https://github.com/olivere/elastic/blob/release-branch.v2/search_aggs_avg_test.go). The [`FilteredQuery`](https://github.com/olivere/elastic/blob/release-branch.v2/search_queries_filtered.go) is simply a combination of a filter and a query, so you might want to look up [`QueryStringQuery`](https://github.com/olivere/elastic/blob/release-branch.v2/search_queries_query_string_test.go) and [`BoolFilter`](https://github.com/olivere/elastic/blob/release-branch.v2/search_filters_bool_test.go) for the example above.

There is also a list of examples of how to use the different aggregations [here](https://github.com/olivere/elastic/blob/release-branch.v2/search_aggs_test.go#L74) (although a bit hard to read because of its length). 

BTW: Is see that you're still on ES 1.x. Remember that `FilteredQuery` is deprecated in ES 2.x and gone in ES 5.x; also, there's not difference any longer between filters and query in ES 2.0 or later--a good thing.

**Comment by andrejvanderzee** [comment]
Thanks, the query I posted was generated by Kibana. After your comment I switched to `olivere/elastic.v3` (for ES 2.x) and was able to rewrite the code with a simple BoolQuery combined with a RangeQuery and an AvgAggregation.

Thumbs up for the great lib it's running stable in our (production) clusters for months without any problems.
