### ISSUE TITLE
SetGzip does not set the "Accept-Encoding" header proper

### ISSUE THREAD

**Issue by wyndhblb** [olivere/elastic#437]
elastic.v5 (for Elasticsearch 5.x) (gopkg.in)

on a given request (the _bulk) request in particular as thats what i've seen... based on a docker install of ES and a MacOS native binary

```
POST /_bulk HTTP/1.1
Host: 127.0.0.1:9200
User-Agent: elastic/5.0.13 (darwin-amd64)
Content-Length: 1493123
Accept: application/json
Accept-Encoding: gzip
```

Even though the initial request is not gzip'ed (i.e. SetGzip(false)) 

The golang http.Transport is defaulted to `DisableCompression = false`

the ctxhttp/http.Client wraper (which uses the default Transport settings) .. the Accept-Encoding is set to gzip ... which for many really small payloads can cause lots of GC issues in both ES and the decoder on the golang side.  I feel that SetGzip(false) should stop the all gzip everywhere.

**Comment by wyndhblb** [comment]
Pull: https://github.com/olivere/elastic/pull/438

**Comment by olivere** [comment]
Thanks for your support. I think we need to review if the `SetGzip` option is required at all, or if we simply leave it to the implementer to pass a correctly configured `HttpClient` to elastic via `[SetHttpClient](https://github.com/olivere/elastic/blob/release-branch.v5/client.go#L358)`.

**Comment by wyndhblb** [comment]
Sounds reasonable, didn't even see that SetHttpClient function.  Since the body is gzipped in the Request Body maker (outside the client), is that a reasonable option?

**Comment by olivere** [comment]
I feel like we should deprecate the `SetGzip(bool)` option and ask clients to instead pass a custom `*http.Client` via `SetHttpClient` instead.

Here's how you pass a HTTP client with compression disabled:

```
hc := &http.Client{
  Transport: &http.Transport{
    DisableCompression: true,
  },
}
client, err := elastic.NewClient(elastic.SetHttpClient(hc))
```

Notice that the trace log will always print `Accept-Encoding: gzip` regardless of whether compression is enabled or not. This is because of the underlying `httputil.DumpRequestOut` (see [here](https://groups.google.com/forum/#!topic/golang-nuts/ms8QNCzew8Q)). If you want to convince yourself that `Accept-Encoding: gzip` is NOT sent when `DisabledCompression` is `true`, use a real HTTP proxy/recorder.

PR #438 does not reliably solve the issue. You could pass a custom `*http.Client` and `SetGzip(...)` wouldn't override that when e.g. the `SetGzip(...)` option is called before `SetHttpClient(...)`.

As there's no official way to deprecate code in Go, I'll mark it as such to [follow best practices](http://golang.rakyll.org/deprecated/) and will remove the `SetGzip(bool)` option in the next major version.

**Comment by olivere** [comment]
@xuanziranhan I'm not sure what you're asking, but yes: If you pass your own transport, you can modify the `*http.Request` any way you want. See [the wiki](https://github.com/olivere/elastic/wiki/HttpTransport).
