### ISSUE TITLE
Duplicates are generated using BulkProcessor API

### ISSUE THREAD

**Issue by balajichandramohan** [olivere/elastic#445]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v3 (for Elasticsearch 2.x)

### Please describe the expected behavior
During Bulk operation, in case of any failure duplicates should not be generated. 

### Please describe the actual behavior
I am using AWS ES service, and on bulk loader sometimes I get 
elastic: Error 504 (Gateway Timeout)
During retries, I think the same data is committed every time but not acknowledged. 

### Any steps to reproduce the behavior?
I use bulk size of 64MB, bulk actions 15k and 10 workers. With that I get  (Gateway Timeout Error), and data is duplicated is ES.

**Comment by olivere** [comment]
There are many edge cases and BulkProcessor will probably never able to do what you want without the help of the application. I explicitly stated this [in the wiki](https://github.com/olivere/elastic/wiki/BulkProcessor#error-handling): "There is no promise from bulk processor other than "we try our best to put your data into Elasticsearch"."

I have no idea how to reproduce the problems you are experiencing because it is way too high-level and application specific. E.g. one reason could be that BulkProcessor will run into retries and your records are not idempotent.

If you need precise control over the insertion process, either try to handle the logic with the error callbacks in BulkProcessor or use your own Bulk service logic (and be sure to check the response as there might be errors reported by ES while the request itself is successful!).
