### ISSUE TITLE
NewRegexpQuery() behavior 

### ISSUE THREAD

**Issue by dhbarman** [olivere/elastic#467]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

Have been testing the behavior of NewRegexpQuery() filter. In some cases, I am not able to use this filter to find the right matches. 

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

I have ES documents which have a string field. 
Let's take one value for that field - 714:21910 714:23016 714:60011 3356:3 3356:9
If I use the regex, ".*714.*", the filter NewRegexpQuery() selects that document. 
If I use the regex, ".*714:21910.*", it does not select. I am not sure if colon (:) is  treated as a special character. 
If I use a regex, "^714.*", it does not select this document. I made sure whitespaces are trimmed. 

### Please describe the actual behavior

I expect regex to work as expected. 

### Any steps to reproduce the behavior?

You can use any of the following values for your string field. 
a) 1299 3491 3491 38040 23969
b) 3356:100 3356:123 3356:575 3356:2009 65004:32934

**Comment by olivere** [comment]
Are you sure the given property is not analyzed? See the ["Why doesn't my query match the document?"](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/query-dsl-term-query.html) question here.

Otherwise, RegexpQuery should behave as [illustrated in the docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/query-dsl-regexp-query.html). Elastic is simply a client, shuffling your query over to Elasticsearch in a (hopefully) correct request.

If that doesn't help, please provide a complete example so that I can reproduce. I'll then re-open the issue.

**Comment by dhbarman** [comment]
I have now made it not analyzed now in mapping. Can run some more regex. Still trying to figure out what regex matching is supported in ES. You could close the ticket. Thanks.

**Comment by olivere** [comment]
The high-level documentation is [here](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/query-dsl-regexp-query.html), and the detailed regexp syntax is [described here](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/query-dsl-regexp-query.html#regexp-syntax).
