### ISSUE TITLE
I need a Get request,but default is POST and can't be modify.

### ISSUE THREAD

**Issue by fangjianwei** [olivere/elastic#47]
In  the search.go,i need a Get request,but default is POST and can't be modify.

The return result is not same when use the get and post,so the 'GET' is required.

```

2015/03/02 15:23:26 POST /vehicles/_search?pretty=true HTTP/1.1
Host: localhost:9200
User-Agent: elastic/1.3.1 (windows-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

```

**Comment by olivere** [comment]
Hi. Can you please post an example of the GET and an example of the POST request and the results to see the difference. I can use them in a test then.

**Comment by fangjianwei** [comment]
```
{
  "from": 0,
  "min_score": 1,
  "query": {
    "match": {
      "_all": {
        "operator": "and",
        "query": "DC"
      }
    }
  },
  "size": 50,
  "sort": [
    {"_score": {"order": "desc"}},
    {"familyName": {"order": "desc"}},
    {"standardName": {"order": "desc"}},
    {"marketDate": {"order": "desc"}},
    {"gearboxName": {"order": "desc"}}
  ],
  "timeout": "10s"
}
```
It return some results when i use get request.
It return no ressults when i use post request.

**Comment by olivere** [comment]
Okay. I'm not sure why this happens. And before I add anything, I need to understand the reason. Okay?

First, there shouldn't be any difference, really. It must have something to do with your setup/network. Is there a proxy involved that may cut the body for HTTP GET requests, or do you have a 1:1 connection to ES without anything in between? Can you somehow check if the GET body arrives at ES, maybe by logging it? I'm not sure if it's in the HTTP spec, but GET requests probably shouldn't have a body (but most clients/servers don't care any submit it anyway)... but maybe that's the problem here.

The Ruby client has a setting called `send_get_body_as` which you can change to `POST`. But as far as I can see it only changes the HTTP method from `GET` to `POST` and doesn't change the serialization. Of course I can add such a setting, but as I said: I want to know first why/when this problem occurs.

In the meantime, can you try the following to see if it does make a difference?

You can inject a different `http.Transport` into Elastic, and provide that with your own `http.Client`. In the transport, you could change the `GET` to `POST`. Can you [please try out this example](https://github.com/olivere/elastic/wiki/HttpTransport) and report back if it solves your problem?

**Comment by fangjianwei** [comment]
Thanks for you answer.
It is my problem.When i click the Get button in poster that plugin of firefox,it hasn't send the body content.

Very very thanks.

**Comment by justinfx** [comment]
Hi. Sorry to ping this old ticket. But after searching for my problem, I came across this exact match. I'm currently using the older v2 release to pair with an ES 1.7.x cluster (which I cant change). But I see this same issue is still present in the master branch. 

Because of the public proxy around this particular ES cluster, we only allow GET requests without auth. That means I need to be able to make _search requests as GET with a body. I see that requests are hard coded to "POST":

https://github.com/olivere/elastic/blob/v2.0.60/search.go#L391

Is there any reason this isn't configurable by some means? Is the official solution to create a custom transport that changes POST to GET?

**Comment by olivere** [comment]
@justinfx Oh well. You should really fix your environment ;-)

I'm trying to find a workaround for you. v2 is deprecated, but maybe we can do a simple quickfix.

**Comment by olivere** [comment]
@justinfx Try 2.0.61, just released.

**Comment by justinfx** [comment]
Wow that was really nice of you to backport support for this! I did get it working with a custom transport, but that is pretty heavy weight.

Is this something you are merging to the tip as well? It could be a problem for anyone, if they need to have this kind of control over the request. Thanks!

**Comment by olivere** [comment]
No, I do not plan to enable that for newer versions. `POST` is the HTTP verb that all official clients use, and there shouldn't be anything in your infrastructure prohibiting you to use `POST` instead of `GET`.

In the early day of Elasticsearch (~0.9), there even was a problem with `GET` in that certain firewalls/proxies/gateways didn't expect `GET` to have a body, so that wouldn't work at all--hence they switched to `POST` by default. I don't know if that's an issue still.

**Comment by olivere** [comment]
Note to self: [Java High Level client uses `POST`](https://github.com/elastic/elasticsearch/blob/master/client/rest-high-level/src/main/java/org/elasticsearch/client/RequestConverters.java#L462) and you cannot change that.

**Comment by justinfx** [comment]
That's ok. Worst case is that the custom transport workaround is still
available.
