### ISSUE TITLE
Elasticsearch Cache key

### ISSUE THREAD

**Issue by wedneyyuri** [olivere/elastic#512]
Hi @olivere, maybe it's a newbie question, but I did not understand how this project handles the [cache key](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html#_cache_key), as far I know the order of the keys generated during the output is not guaranted.

> The whole JSON body is used as the cache key. This means that if the JSON changes — for instance if keys are output in a different order — then the cache key will not be recognised. Most JSON libraries support a canonical mode which ensures that JSON keys are always emitted in the same order. This canonical mode can be used in the application to ensure that a request is always serialized in the same way.
> https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html#_cache_key

**Comment by olivere** [comment]
Elastic uses encoding/json under its covers. And that doesn't have any form of canonicalization mode AFAIK (it's not necessary according to RFC4627 describing the JSON format). Related discussion: https://groups.google.com/forum/m/#!topic/golang-dev/zBQwhm3VfvU

So I'm afraid Elastic isn't a good citizen in this regard. But I need to lookup the cache_key docs, because I remember it was possible to manually pass the cache key (I can't remember the details right now).

**Comment by wedneyyuri** [comment]
Hi @olivere, any news?

Sorry, but I didn't find the cache_key docs.

**Comment by olivere** [comment]
@wedneyyuri The only offical docs that there are available are [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html#_cache_key).

In although `encoding/json` has no canonical mode, all the tests use JSON exactly in that mode and it has never failed (it has literally a hundred tests [like this](https://github.com/olivere/elastic/blob/release-branch.v5/search_aggs_bucket_terms_test.go#L12-L27)). Keys are in alphabetical order, so I assume that Elastic generates good cachable keys. At least I've never seen any issues with this.

I can remember that once it was possible to pass you own cache key, but those days seem to have been gone.
