### ISSUE TITLE
match_phrase_prefix

### ISSUE THREAD

**Issue by philsturgeon** [olivere/elastic#53]
I've been trying out a bazillion different different searches and it seems like I want `match_phrase_prefix`, but this client is lacking it. 

I can either mash this out and probably arse it up, or I can donate $20 to the charity of your choice, which could be your bartender, if you do this for me. 

http://www.elastic.co/guide/en/elasticsearch/guide/current/_query_time_search_as_you_type.html

**Comment by olivere** [comment]
:-)

The `match_phrase_prefix` query is already available. It's just that you need to initiate it in a special way. There are two ways of creating the various match query types according to [the documentation](http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#_match_phrase_prefix). The API just seems to support the latter. I've mimicked most of the API of the Java client, so that's probably why it's confusing.

Here's an example:

```go
q := elastic.NewMatchQuery("this is a test", "message").Type("phrase_prefix")
```

You can find the [code here](https://github.com/olivere/elastic/blob/master/search_queries_match.go) and a [test case here](https://github.com/olivere/elastic/blob/master/search_queries_multi_match_test.go#L77) (for MultiMatchQuery though).

If that doesn't help you, let me know and I'll see what I can do. 

Regarding the donation: If you want to do a good deed, I won't stand in your way. I'm sure you find something that you're personally interested in at e.g. [Give Well](http://www.givewell.org/).

**Comment by olivere** [comment]
I added shortcut methods `NewMatchPhraseQuery` and `NewMatchPhrasePrefixQuery` to (hopefully) make things clearer to the next Elastic user.
