### ISSUE TITLE
mapping parent child

### ISSUE THREAD

**Issue by aneukNanggroe** [olivere/elastic#559]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[-] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior
putmapping, i want put mapping with parent child

### Please describe the actual behavior
for now, when put mapping, only one type, but if i need put more type(parent child mapping) it showing error

### Any steps to reproduce the behavior?
how can i do mapping parent child?

**Comment by olivere** [comment]
There is great documentation about parent/child on the Elasticsearch web site, e.g. [documentation on the `_parent` field](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/mapping-parent-field.html).

This repository is special to the Go client for Elasticsearch. If you find a problem with this, first make sure that it does work in Elasticsearch, conceptually. If that does work and you struggle with the Go client, please post a code snippet so that we can reproduce what's wrong. Thanks.
