### ISSUE TITLE
DeleteByQuery ElasticSearch Golang error elastic: Error 404 (Not Found)

### ISSUE THREAD

**Issue by dhawal-tolexo** [olivere/elastic#572]
I'm trying to delete the documents from my Index with specific productIDs. 

Here's the sample code:

    package main
    
    import (
    	"encoding/json"
    	"log"
    	"time"
    	"fmt"
    	"gopkg.in/mgo.v2/bson"
    	elastic "gopkg.in/olivere/elastic.v3"
    )
    
    func main() {
    
    	client, err := elastic.NewClient(elastic.SetSniff(false), elastic.SetURL("http://localhost:9200"))
    	if err != nil {
    		log.Fatal("Cannot create ES client:", err)
    	}
    	boolQuery := elastic.NewBoolQuery().Must(elastic.NewTermQuery("productId", "1503368"))
    
    	searchQuery := client.Search().Query(boolQuery).
    		Index("magento1").Type("catalog")
    	result, err := searchQuery.Do()
    	for _, hit := range result.Hits.Hits {
    		var data bson.M
    		_ = json.Unmarshal(*hit.Source, &data)
    		fmt.Println("SEARCH RESPONSE\n", data)
    	}
    
    	result2, err2 := elastic.NewDeleteByQueryService(client).
    		Index("magento1").
    		Type("catalog").
    		Query(boolQuery).
    		Do()
    	fmt.Println("DELETE RESPONSE 2: \n", result2, err2)
    
    }

The SearchQuery gives the correct response and returns me the document with the provided productId (I DID THIS JUST TO VERIFY IF THE DOCUMENT EXISTS OR NOT).

Now the deletion, I don't know what on earth is wrong with the code or if there's anything missing in the API or something extra has to be added (matchAll etc) but this delete Query is just not deleting the Index AND always giving me the response:

    error elastic: Error 404 (Not Found)

I've searched all the blogs/docs/official library's GitHub [tests](https://github.com/olivere/elastic/blob/release-branch.v5/delete_by_query.go) cases etc but none resolved my problem. Although I've come to a resolution to Scan/Scroll and Bulk delete still wonder why this is not working if it's in the official documentation. 

Here's the mapping:

    "productId": bson.M{"type": "string", "store": true, "index": "not_analyzed"},

ES VERSION:
`5.3.1`

Thanks.

**Comment by olivere** [comment]
First of all, your example uses `elastic.v3` but in the end you state that you're using `5.3.1`. Please make sure you use the correct version of Elastic: v3 is for ES 2.x, v5 is for ES 5.x.

Next, I'm not sure about your mapping. You're using `bson.M` which is Mongo-parlance. While it might work with mapping stuff in ES (because `bson.M` is simply a map after all), this leaves me confused about your mapping.

Finally, it's a rough guess, because I can't reproduce your issue with the code above (e.g. because the code doesn't set up the mapping): ES is not a database. It's a search engine specifically used to deal with human language. When you're using a `string` type, it's very probable that it's not what you think it is. In v6 there even will be not `string` type, there's only `keyword` and `text`. In v5, the `string` type is actually [this mapping](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/breaking_50_mapping_changes.html#_literal_string_literal_fields_replaced_by_literal_text_literal_literal_keyword_literal_fields).

So, if you want to delete an exact term match (like in a `TermQuery`), you probably want to delete with `productId.keyword`equals to `"1503368"`.

```
query := elastic.NewTermQuery("productId.keyword", "1503368")
```

Furthermore, `DeleteByQuery` uses the Bulk API to delete documents. That's fairly inefficient when you only want to delete a single document. You should better delete by document ID, if you can.

**Comment by dhawal-tolexo** [comment]
Hi, yeah i somehow always thought `elastic.v3` is for `ES 5 .3.1`. Although i can't confirm this since i need golang `1.7` for `elastic.v5` (i have `golang 1.5.1`) i believe this should work. 

Currently i've already resorted to using `scan/scroll` with `bulk delete by id` and it works fine with `bson,M` since as you said its a `map[string]interface{}` after all.

Since the `productId` is `not_analyzed` i guess its a keyword (string) and not a text after the mapping.
