### ISSUE TITLE
sort.ignore_unmapped

### ISSUE THREAD

**Issue by zhanghuibin2013** [olivere/elastic#638]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v5 (for Elasticsearch 5.x)

### Please describe the expected behavior

Elasticsearch 5.x的search似乎不再支持 sort.ignore_unmapped ，改为 sort.unmapped_type了，需要elastic.v5做对应的升级
### Please describe the actual behavior

Error 400 (Bad Request): [field_sort] unknown field [ignore_unmapped], parser not found [type=illegal_argument_exception]

**Comment by olivere** [comment]
The `unmapped_type` has been there since at least 5.0. It is supported for [FieldSort](https://github.com/elastic/elasticsearch/blob/ba024855410b88cbdcfd9ac3b582a5b53b28d45a/core/src/main/java/org/elasticsearch/search/sort/FieldSortBuilder.java#L58).

However, it seems that `ignore_unmapped` has been removed a long time ago. I will remove it as well.

**Comment by olivere** [comment]
Here's the [changes to v6](https://github.com/olivere/elastic/commit/14940c7fc9fdee2dd4646564bf1ddba622a0d3ed) and [v5](https://github.com/olivere/elastic/commit/9ebac83f3695d95db4347125f24540559e2c5f66).

It will be included in the next release.
