### ISSUE TITLE
Bucket Sort Aggregation not available for elastic.v6

### ISSUE THREAD

**Issue by mmfrb** [olivere/elastic#730]
### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
I'd like to use the brand new [Bucket Sort Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search-aggregations-pipeline-bucket-sort-aggregation.html)  through the elastic client.

### Please describe the actual behavior
Apparently this is not implemented yet nor will be released in the next release (at least I could not find it in the files of the branch).

This is more of a question of whether this is already being implemented. I'd be more than happy to implement it myself, and if that's the case, some instructions on how to implement a new pipeline aggregation would be much appreciated.

Thanks in advance

**Comment by olivere** [comment]
Yes, it looks like that's still missing.

If you have the time and commitment to become a contributor, here's a few tips. Aggregations have two sides: The query-side, which is what you find in e.g. `search_aggs_pipeline_avg_bucket.go` (and its test file), and the response-side, which extracts the aggregated data from the response (you find that in `search_aggs.go` and its test file). We've recently added a few missing aggregation types, so that should give you a blueprint of what it takes to add a new aggregation type (see e.g. [this PR](https://github.com/olivere/elastic/pull/725)).

Otherwise, don't worry. I'll add it to the backlog and will add it in one of the next releases.

**Comment by mmfrb** [comment]
I have the pull request ready. Could you please give me permission to push my branch into the repo?

**Comment by olivere** [comment]
@mmfrb That's not how it works. You need to fork this repository first, then work on your fork, and finally send me a Pull Request to review. Once it's looking good, I will then merge it into this repository.

See [here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) for details. This is also quite a [good reference](https://gist.github.com/Chaser324/ce0505fbed06b947d962).

**Comment by olivere** [comment]
Merged in #732, thank you. It will be available in the next release of v6.
