### ISSUE TITLE
Reset client ?

### ISSUE THREAD

**Issue by yuva29** [olivere/elastic#740]
Let us say my elasticsearch nodes are running as kubernetes pods. It is possible that **all** the pods may go down and come back again with a different IP. In that case, the client is not running anymore. Is that right? 

Is there any way to internally reset the client, may be in a retrier with the new URL(s)?

**Comment by olivere** [comment]
Okay, that's an interesting problem.

When creating a client with Elastic, you need to pass a URL to at least one node of the cluster so that Elastic has a chance to at least connect. If you enable sniffing (the default), Elastic inspects the cluster and finds all other nodes and stores them as possible targets to send requests to.

However, if at any point in time, all pods are gone, all internal connection states have gone to status "dead". When a request is then sent via Elastic, it tries to pick a connection from the "dead" and retries with the other connections is has according to the configured retrier and backoff.

However, if the cluster comes up again with all nodes having different IPs, Elastic has no way of ever finding the nodes in the re-configured cluster.

Currently, I only see these solutions:

1. Use a load balancer / dedicated node in front of the rest of the cluster. HAProxy or nginx come to mind.
2. Experiment withdedicated [coordinating nodes](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#coordinating-node) in Elasticsearch and ensure they don't get removed in the Kubernetes cluster.

The long-term solution would be support in Elastic for different (sniffing) strategies of finding nodes in the cluster (in k8s you could e.g. search for pods with certain tags), along with supporting different LB strategies (currently, there is only round-robin).

**Comment by olivere** [comment]
But coming back to your original question: Is there a way to reset the client?

Yes, you should simply call `client.Stop()` to halt all goroutines that started when creating the "old" client, then create a new `*Client`.

You could also use the stateless `elastic.NewSimpleClient`, which creates a "throwaway" client.

**Comment by yuva29** [comment]
@olivere Thank you for the quick response.

Regarding the solutions you mentioned.
1. Use a load balancer / dedicated node 
    - the elastic client becomes more of a simple client as there is no distribution (round-robin) or sniffing required. The requests are always sent to the balancer. Please correct me If i'm wrong.
   - The problem remains the same if this load balancer is also run as a pod.
2. Pods can be removed and re-scheduled anywhere in the cluster. K8s does not guarantee anything on that.

I retried resetting the client in retrier when the request fails with an option to let the caller retry the request again which seems to work. I'll explore that option further.

**Comment by olivere** [comment]
Hmm... may I ask how you run ES on Kubernetes? Do you expose ES via a k8s service with `type: loadBalancer`? If that is true then you should be able to run Elastic with the service endpoint, no? Just be sure to disable sniffing.

**Comment by yuva29** [comment]
No. We don't want to expose it as a service due to some restrictions.

**Comment by olivere** [comment]
Do you have a link on the internet which describes how you run ES on Kubernetes?

**Comment by yuva29** [comment]
Not exactly. We have a customized solution using deployment/daemon sets and file-based discovery plugin. The ES cluster is not backed by k8s service today.

**Comment by olivere** [comment]
Okay. If I understand you correctly, you know the IP addresses of the ES nodes at any time, but they are not accessible by DNS or hostname? Hence you want to create a new ES client once the IPs change?

**Comment by yuva29** [comment]
Yes. That's right.

**Comment by olivere** [comment]
Okay. Then I think you currently do only have 2 options:

1. Create a new long-running client with `elastic.NewClient` whenever your cluster "dies".
2. Use `elastic.NewSimpleClient` which is request-scoped.

HTH.
