### ISSUE TITLE
DeleteIndex whats the error type returned if index already exists

### ISSUE THREAD

**Issue by pratapan9** [olivere/elastic#741]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[X ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
elastic client 'DeleteIndex' method.. I want to know whats the error type returned when Index already exists.. I want to check for that error type in my code.. Can you direct me where that error type is defined?

**Comment by olivere** [comment]
If the index already exists and you call `DeleteIndex`, the index is successfully deleted. Or do you mean what happens if you try to delete when the index does *not* exist? I think it will return with status code `404`, which you can test with e.g. [`elastic.IsNotFound(err)`](https://github.com/olivere/elastic/blob/release-branch.v6/errors.go#L100-L105). I typically do an [`IndexExists`](https://github.com/olivere/elastic/blob/release-branch.v6/indices_exists.go) instead: You can find [an example here](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/bulk_processor/main.go#L58-L68).
