### ISSUE TITLE
Disable sniffing by default in 7.x: Yes or no?

### ISSUE THREAD

**Issue by olivere** [olivere/elastic#823]
By far the most frequently asked question is why there is an `elastic. ErrNoClient` error: `elastic: no Elasticsearch node available`. The reason for that is [described in detail in the Wiki](https://github.com/olivere/elastic/wiki/Connection-Problems).

It remains an open question if it would be better to 

a) make people hit the wall and make them ask about sniffing (the situation today) or
b) disable sniffing by default in 7.x so that it just works (tm) but would possibly break in production when a single node goes down in your cluster.

Feel free to comment if you have an opinion.

**Comment by Comradin** [comment]
Some days ago, when reading the issue emails, I noticed the same fact. Every second issue was answered with the hint to disable sniffing or understand und use it correctly.

Maybe add a check for the node address and if it is localhost, 127.0.0.1, ::1 (ipv6) and then disable it by default?

My guess is, that the error triggers most times on someones computer during development. And at the very moment, when the code hits production, sniffing would be a great option, someone would like to have active.

But at least, with disabled sniffing, the code would run in production with the specified node, while it wouldn't fail any longer in development?

**Comment by olivere** [comment]
@Comradin Yes, it would work in both environments. However, people might start to claim that it fails in production which is much worse than failing in development, of course. Maybe it would be a good idea to have the code break at compile time when switching to 7.x so that developers would be forced to make a sensible decision.

I would also like to extract the node-selection and (maybe) the scheduling algorithm, so that everyone can provide their own way to find the nodes of the cluster. Some might simply rely on DNS, some want Elastic to sniff the cluster, some have a static IP pool of nodes etc.

**Comment by slawo** [comment]
I got bit by this yesterday after having not used es for some time. Despite this I really believe it should not be disabled by default.

For those who want to start using the driver with a quick example this flag could be given in the main first example with a link to documentation about it

**Comment by patgmiller** [comment]
I am curious to know if the sniffing and health checks built into the client are solely for the purpose of providing reliability by default. At least that's what the documentation leads me to believe. So that if I am using Elastic to connect to an ElasticSearch cluster which is already behind a service in an environment that provides load balancing and health-checks, like kubernetes for example, then the sniffing feature should be disabled, am I correct?

**Comment by olivere** [comment]
Correct. If you already have a mechanism to provide load-balancing/healthchecks, you should turn sniffing off. E.g. you could use haproxy or nginx.

**Comment by olivere** [comment]
I generally think that server-side solutions are better than what Elastic provides by default.

**Comment by patgmiller** [comment]
Thanks, that's helpful 👍

**Comment by telendt** [comment]
I'm in favor of option **b** - disabling sniffing by default. As mentioned previously here, there are many setups where sniffing causes issues and  IMO enabling sniffing should be a conscious user decision. AFAIK this also matches the default behavior of an official Java client.

**Comment by olivere** [comment]
While I was all for disabling sniffing as well in v7, I ultimately decided against it. In the end, this is the last major version of Elastic (there's an [official client now](https://github.com/elastic/go-elasticsearch)), and it'd probably do more harm to change defaults in this version.

**Comment by telendt** [comment]
The official client badly missed DSL builders IMHO.

**Comment by olivere** [comment]
Yes. And it’ll probably stay like that until there will be a spec for request and response types, just like there is for the endpoints. Unfortunately I don’t know the status of that task.

**Comment by ahmadtanhaa** [comment]
Hi, @olivere 
I have a similar problem while using Monstache. I encounter the following error:

**Unable to create Elasticsearch client: health check timeout: no Elasticsearch node available**

I found that the problem is that I can not get Elastic to connect to an Elasticsearch node or cluster and I read [your WIKI guide](https://github.com/olivere/elastic/wiki/Connection-Problems), however, I want to know how  I can use "github.com/olivere/elastic/v7" as an import path? I mean where these configs should be written?:

// Create a client for Elasticsearch 7.x

import (
  "net/http"

  "github.com/olivere/elastic/v7"
)

...
// Create a client
client, err := elastic.NewClient()
if err != nil {
  // Handle error
  panic(err)
}
...

**Comment by olivere** [comment]
@ahmad-tanha You can find several examples in the [`recipes`](https://github.com/olivere/elastic/blob/release-branch.v7/recipes) directory, e.g. [`connect.go`](https://github.com/olivere/elastic/blob/release-branch.v7/recipes/connect/connect.go).
