### ISSUE TITLE
ScrollService not returning MaxScore and individual Hits Score

### ISSUE THREAD

**Issue by Suresh-Nakkeran** [olivere/elastic#838]
when I tried to search with SearchService, the response had max score and individual hit score. But when I tried the same query in ScrollService, the response had nil max score and hit score... Any one have solution for this issue?

**Comment by olivere** [comment]
I have to dig into the details to be sure, but I guess it's due to performance optimization. Scrolling is not meant to be used for real-time use. The docs state:

> Scrolling is not intended for real time user requests, but rather for processing large amounts of data, e.g. in order to reindex the contents of one index into a new index with a different configuration.

So I guess they don't calculate scores when scrolling.

Please feel free to confirm this yourself by asking in the [official Elasticsearch forum](https://discuss.elastic.co/).
