### ISSUE TITLE
Help with query_string (NOT ISSUE)

### ISSUE THREAD

**Issue by goors** [olivere/elastic#89]
Hi,

I am struggling with search. What I need is to duplicate this:
<pre>
   {
        "query":{
            "query_string":{
                 "query":"Search for something",
                 "fields":["RouteName"]
           }
     }
}
</pre>
I was trying with:
<pre> termQuery := elastic.NewSearchSource().Fields("Content","Description","RouteName","Category","Km","Level","County")</pre>

but I do not know how to pass data and query_string.
Fro the error I am getting I can see that I am doing this in wrong way.

Thanks.

**Comment by goors** [comment]
Is thre anyway that I can use raw json:
<pre>
searchJson := `{
		"query" : {
			"query_string" : {
			 "query":`+data+`,
			 "fields":["Content","Description","RouteName","Category","Km","Level","County"]
			 }
		}
	}`
</pre>

**Comment by olivere** [comment]
Hi. That's two questions.

First, you can create a [QueryStringQuery](https://github.com/olivere/elastic/blob/master/search_queries_query_string.go) as described in [this test](https://github.com/olivere/elastic/blob/master/search_queries_query_string_test.go). Here's an example of what you're trying to achieve (can't test it because I have no ES at hand, sorry):

```
q := elastic.NewQueryStringQuery("Search for something")
q = q.Field("Content").Field("Description") // etc.
results, err := client.Search().Index("indexname").Query(q).Do()
// check err and search results here
```

If you want to send a raw query to the search service, you can do something along these lines:

```
res, err := client.Search().Index("indexname").Source(rawBody).Do()
// check err and search results here
```

Let me know if that doesn't work for you. Cheers.

**Comment by goors** [comment]
Thank you. You saved my day! Both answers work perfectly!
