### ISSUE TITLE
Do you know how we can implement concurrency in elasicsearch go client? Ex: I want to create multiple objects of elastic search go client and assign each object to one thread to query elasticsearch and produce the result. I am currently using ElasticSearch V6.X

### ISSUE THREAD

**Issue by rohitravi22** [olivere/elastic#935]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

**Comment by olivere** [comment]
Do not create multiple clients. A client is thread-safe by design, so you can use it in multiple Go routines without any problems. Simple pass one instance of `*elastic.Client` around.

There are various reasons for that. One is that each client creates a set of goroutines that run in the background. If you create many clients, they will stand on each others foots, maybe.

If you want to use concurrency in Go with this library, use e.g. something like the pipeline example of [`errgroup.Group`](https://godoc.org/golang.org/x/sync/errgroup). Here's [an example of bulk indexing](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/bulk_insert/bulk_insert.go) or [concurrent slicing](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/sliced_scroll/sliced_scroll.go). See also the [wiki](https://github.com/olivere/elastic/wiki).
