### ISSUE TITLE
Execution time is very slow

### ISSUE THREAD

**Issue by alexandremottet** [olivere/elastic#944]
### Which version of Elastic are you using?

[-] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the actual behavior
When I index a document with a direct call (request bellow) to elasticsearch (using postman), elasticsearch take around 10ms each time to index the document or at least to send the response.
``` 
PUT - http://localhost:9200/courses-en/doc/1
{
	"title" : "test",
	"description" : "test",
	"text" : "test",
	"tags": []
}
```

However, when I use this client, it took between 500ms and 1000ms to reponsed.

I use the following execution time ```start := time.Now()  / elapsed := time.Since(start)``` to nearly down the line that take this time :
```
_, err := es.client.Index().
  Index(index).
  Type("doc").
  Id(identifier).
  BodyJson(doc).
  Refresh("wait_for").
  Do(es.context)
```

### Please describe the expected behavior
Having nearly the same response speed as a direct call to elasticsearch

### Any steps to reproduce the behavior?
I use :
- a docker image to create the elasticsearch
- the code from the example : https://gist.github.com/olivere/e4a376b4783c0914e44ea4f745ce2ebf

**Comment by olivere** [comment]
If you test two systems, you must at least do the same thing. E.g. in your Go version you're specifying `Refresh("wait_for")` which you don't in the `curl` case. Also, there might be overhead at the beginning due to the process of finding the nodes in the cluster etc. This looks very much like a microbenchmark which probably doesn't have too much of an impact once you're running a real work load.

**Comment by alexandremottet** [comment]
Indeed, I thought "wait_for" was a mandatory parameter for the client and not for elasticsearch.
Thanks
