### ISSUE TITLE
Would it be possible to change the match query (and derivatives) to support multiple query strings ?

### ISSUE THREAD

**Issue by orangemail** [olivere/elastic#952]
Would it be possible to change the match query (and derivatives) to support multiple query strings ?

{ match: { tag: ['foo',bar']}}
{ match: { num: [1,2,3]}}

Or even a workaround way to implement this kind of query is much appreciated .. ?
(i.e)
For terms query we have 
func NewTermsQuery(name string, values ...interface{}) *TermsQuery
we needs something similar for match query too ..

**Comment by olivere** [comment]
Can you lead me to the official [QueryDSL documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/query-dsl.html) page that illustrates your feature request.

If I can find the feature there, we can see if it's already implemented or we need to add a new query type.

Otherwise I think a workaround might be to use the [Multi Search API](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/search-multi-search.html) (implemented in [`multi_search.go`](https://github.com/olivere/elastic/blob/release-branch.v6/msearch.go)) and send multiple search requests in one network roundtrip. But that might of course not be what you want.

**Comment by orangemail** [comment]
Thanks Olivere... I think possible workaround for match query case is form a single single with multiple values saparated by comma or space. 

value  = "value1,value2,value3"
i.e query = query.Must(elastic.NewMatchQuery("Parameter", Value))

I tired both space and comma as delimiter between values both are working.  If you have any better  solution you can suggest ? Else you can close this Issue.

**Comment by olivere** [comment]
You should look at the official documentation for the supported features. Besides that, the „correct“ solution largely depends on your use case, mappings etc. That’d be consulting.
