### ISSUE TITLE
Forbidden when connecting to AWS ES with IAM

### ISSUE THREAD

**Issue by bubenkoff** [olivere/elastic#962]
using the approach from https://github.com/olivere/elastic/blob/release-branch.v6/recipes/aws-connect-v4/main.go
I'm getting 403 forbidden
while with https://github.com/sha1sum/aws_signing_client it connects fine

### Which version of Elastic are you using?

[X ] elastic.v6 (for Elasticsearch 6.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v2 (for Elasticsearch 1.x)

### Please describe the expected behavior

using the approach from https://github.com/olivere/elastic/blob/release-branch.v6/recipes/aws-connect-v4/main.go

expecting the successfull calls

### Please describe the actual behavior

Getting 403 Forbidden when calling the service

### Any steps to reproduce the behavior?

https://github.com/olivere/elastic/blob/release-branch.v6/recipes/aws-connect-v4/main.go

**Comment by olivere** [comment]
Sorry for the delay. I'm on a business trip right now and don't have the ability to spin up an AWS cluster right now. Didn't forget about it…

**Comment by olivere** [comment]
I finally had the time to figure out what was going on here. This should be fixed in 6.2.14, and I've successfully tested it on a live AWS Elasticsearch service cluster. I've added a new [`aws-mapping-v4` recipe](https://github.com/olivere/elastic/blob/release-branch.v6/recipes/aws-mapping-v4/main.go) for testing on AWS Elasticsearch service.

**Comment by wesleyk** [comment]
👏 👏 👏 Thank you!
